// GENERATED FILE — do not edit by hand. Run `pnpm gen:variant-parts`.
import { variantsA } from "./variants.a";
import { variantsB } from "./variants.b";

export const variants = {
    "footer-large-01": variantsA["footer-large-01"],
    "footer-large-04": variantsA["footer-large-04"],
    "footer-large-07": variantsA["footer-large-07"],
    "footer-large-10": variantsA["footer-large-10"],
    "footer-large-13": variantsA["footer-large-13"],
    "footer-large-16": variantsA["footer-large-16"],
    "footer-small-03": variantsA["footer-small-03"],
    "footer-large-02-brand": variantsA["footer-large-02-brand"],
    "footer-large-05-brand": variantsA["footer-large-05-brand"],
    "footer-large-08-brand": variantsA["footer-large-08-brand"],
    "footer-large-11-brand": variantsA["footer-large-11-brand"],
    "footer-large-14-brand": variantsA["footer-large-14-brand"],
    "footer-small-01-brand": variantsA["footer-small-01-brand"],
    "footer-small-04-brand": variantsA["footer-small-04-brand"],
    "footer-large-02": variantsA["footer-large-02"],
    "footer-large-05": variantsA["footer-large-05"],
    "footer-large-08": variantsA["footer-large-08"],
    "footer-large-11": variantsA["footer-large-11"],
    "footer-large-14": variantsA["footer-large-14"],
    "footer-small-01": variantsA["footer-small-01"],
    "footer-small-04": variantsB["footer-small-04"],
    "footer-large-03-brand": variantsB["footer-large-03-brand"],
    "footer-large-06-brand": variantsB["footer-large-06-brand"],
    "footer-large-09-brand": variantsB["footer-large-09-brand"],
    "footer-large-12-brand": variantsB["footer-large-12-brand"],
    "footer-large-15-brand": variantsB["footer-large-15-brand"],
    "footer-small-02-brand": variantsB["footer-small-02-brand"],
    "footer-large-03": variantsB["footer-large-03"],
    "footer-large-06": variantsB["footer-large-06"],
    "footer-large-09": variantsB["footer-large-09"],
    "footer-large-12": variantsB["footer-large-12"],
    "footer-large-15": variantsB["footer-large-15"],
    "footer-small-02": variantsB["footer-small-02"],
    "footer-large-01-brand": variantsB["footer-large-01-brand"],
    "footer-large-04-brand": variantsB["footer-large-04-brand"],
    "footer-large-07-brand": variantsB["footer-large-07-brand"],
    "footer-large-10-brand": variantsB["footer-large-10-brand"],
    "footer-large-13-brand": variantsB["footer-large-13-brand"],
    "footer-large-16-brand": variantsB["footer-large-16-brand"],
    "footer-small-03-brand": variantsB["footer-small-03-brand"],
} as const;
