/**
 * Every fact the landing page states, in one place.
 *
 * The counts are measured, not marketing — they come from `packages/registry/dist/stats.json`,
 * generated by `pnpm registry:build` (see `packages/registry/src/build.ts`, "Stats" section).
 * That file is the single source for these numbers: README.md's count sentence
 * (`scripts/gen-stats-readme.ts`) and this module both read it, so they can never disagree.
 * Re-derive by running `pnpm registry:build`, then `pnpm gen:stats` to refresh the README.
 */
import registryStats from "../../../../packages/registry/dist/stats.json";

/** Canonical origin. The registry and `/llms.txt` below are the URLs an agent is pointed at. */
export const SITE_ORIGIN = "https://smarteraui.com";

/** Where the CLI resolves components from by default, and what an agent can fetch directly. */
export const REGISTRY_URL = `${SITE_ORIGIN}/r`;

/** The index an LLM crawls to find the plain-markdown twin of every documentation page. */
export const LLMS_TXT_URL = `${SITE_ORIGIN}/llms.txt`;

/** Every entry in `packages/registry/dist/index.json` — components, examples, hooks, utils and styles. */
export const REGISTRY_ENTRIES = registryStats.entries;

/** Public repository. Deliberately local to the landing page: `~/lib/site` still points at the docs org. */
export const REPO_URL = "https://github.com/aymanshabaro/smarteraui";

/** The npm package the install snippet adds. */
export const PACKAGE_NAME = "@smarteraui/ui";

export const INSTALL_COMMAND = `npm i ${PACKAGE_NAME}`;

/** Component groups per published layer — one folder in `packages/ui/src/components/<layer>`, one registry `component` entry. */
export const LAYER_COUNTS = {
    base: registryStats.groups.byLayer.base,
    application: registryStats.groups.byLayer.application,
    marketing: registryStats.groups.byLayer.marketing,
} as const;

/** Component groups across the three published layers (base + application + marketing). Matches `groups.published` in stats.json. */
export const COMPONENT_GROUPS = registryStats.groups.published;

/** Registry `example` entries in the `marketing` layer — the section variants. */
export const SECTION_VARIANTS = registryStats.variants;

/** Registry `example` entries in the `marketing-examples` layer — complete marketing pages. */
export const MARKETING_PAGE_EXAMPLES = registryStats.examples.marketing;

/** Registry `example` entries in the `app-examples` layer — dashboards, settings and auth pages. */
export const APP_PAGE_EXAMPLES = registryStats.examples.app;

/** Every full page example, across both layers. */
export const PAGE_EXAMPLES = registryStats.examples.total;

/** Vitest suites under `packages/ui/src/components`; every one of them asserts zero axe violations. */
export const TEST_SUITES = registryStats.testSuites;

/** Section variants and full page examples together — everything an agent can compose a screen from. */
export const COMPOSABLE_VARIANTS = SECTION_VARIANTS + PAGE_EXAMPLES;
