// GENERATED FILE — do not edit by hand. Run `pnpm gen:demos`.
import type { ComponentType } from "react";
import * as d0 from "@properui/ui/components/app-examples/404-sections/404-sections.demo";
import * as d1 from "@properui/ui/components/app-examples/dashboards-02/dashboards-02.demo";
import * as d2 from "@properui/ui/components/app-examples/dashboards/dashboards.demo";
import * as d3 from "@properui/ui/components/app-examples/email-templates/email-templates.demo";
import * as d4 from "@properui/ui/components/app-examples/forgot-password-pages/forgot-password-pages.demo";
import * as d5 from "@properui/ui/components/app-examples/informational-pages-02/informational-pages-02.demo";
import * as d6 from "@properui/ui/components/app-examples/informational-pages/informational-pages.demo";
import * as d7 from "@properui/ui/components/app-examples/log-in-pages/log-in-pages.demo";
import * as d8 from "@properui/ui/components/app-examples/settings-pages-02/settings-pages-02.demo";
import * as d9 from "@properui/ui/components/app-examples/settings-pages/settings-pages.demo";
import * as d10 from "@properui/ui/components/app-examples/sign-up-pages/sign-up-pages.demo";
import * as d11 from "@properui/ui/components/app-examples/verification-pages/verification-pages.demo";
import * as d12 from "@properui/ui/components/application/activity-feed/activity-feed.demo";
import * as d13 from "@properui/ui/components/application/alerts/alerts.demo";
import * as d14 from "@properui/ui/components/application/app-navigation/header-navigation.demo";
import * as d15 from "@properui/ui/components/application/app-navigation/sidebar-navigation.demo";
import * as d16 from "@properui/ui/components/application/breadcrumbs/breadcrumbs.demo";
import * as d17 from "@properui/ui/components/application/callout/callout.demo";
import * as d18 from "@properui/ui/components/application/card-headers/card-headers.demo";
import * as d19 from "@properui/ui/components/application/carousel/carousel.demo";
import * as d20 from "@properui/ui/components/application/charts/activity-gauges.demo";
import * as d21 from "@properui/ui/components/application/charts/line-bar-charts.demo";
import * as d22 from "@properui/ui/components/application/charts/pie-charts.demo";
import * as d23 from "@properui/ui/components/application/charts/radar-charts.demo";
import * as d24 from "@properui/ui/components/application/code-snippet/code-snippet.demo";
import * as d25 from "@properui/ui/components/application/color-picker/color-picker.demo";
import * as d26 from "@properui/ui/components/application/command-menu/command-menu.demo";
import * as d27 from "@properui/ui/components/application/confirm-dialog/confirm-dialog.demo";
import * as d28 from "@properui/ui/components/application/content-divider/content-divider.demo";
import * as d29 from "@properui/ui/components/application/date-picker/calendar.demo";
import * as d30 from "@properui/ui/components/application/date-picker/date-pickers.demo";
import * as d31 from "@properui/ui/components/application/description-list/description-list.demo";
import * as d32 from "@properui/ui/components/application/empty-state/empty-state.demo";
import * as d33 from "@properui/ui/components/application/file-upload/file-upload.demo";
import * as d34 from "@properui/ui/components/application/filter-bar/filter-bars.demo";
import * as d35 from "@properui/ui/components/application/gradient-picker/gradient-picker.demo";
import * as d36 from "@properui/ui/components/application/image-picker/image-picker.demo";
import * as d37 from "@properui/ui/components/application/inline-cta/inline-cta.demo";
import * as d38 from "@properui/ui/components/application/loading-indicator/loading-indicator.demo";
import * as d39 from "@properui/ui/components/application/messaging/messaging.demo";
import * as d40 from "@properui/ui/components/application/metrics/metrics.demo";
import * as d41 from "@properui/ui/components/application/modals/modals.demo";
import * as d42 from "@properui/ui/components/application/notifications/notifications.demo";
import * as d43 from "@properui/ui/components/application/page-headers/page-headers.demo";
import * as d44 from "@properui/ui/components/application/pagination/pagination.demo";
import * as d45 from "@properui/ui/components/application/progress-steps/progress-steps.demo";
import * as d46 from "@properui/ui/components/application/section-footers/section-footers.demo";
import * as d47 from "@properui/ui/components/application/section-headers/section-headers.demo";
import * as d48 from "@properui/ui/components/application/slideout-menus/slideout-menus.demo";
import * as d49 from "@properui/ui/components/application/table/table.demo";
import * as d50 from "@properui/ui/components/application/tabs/tabs.demo";
import * as d51 from "@properui/ui/components/application/tree-view/tree-view.demo";
import * as d52 from "@properui/ui/components/base/avatar/avatar.demo";
import * as d53 from "@properui/ui/components/base/badges/badge-groups.demo";
import * as d54 from "@properui/ui/components/base/badges/badges.demo";
import * as d55 from "@properui/ui/components/base/button-group/button-group.demo";
import * as d56 from "@properui/ui/components/base/buttons/app-store-buttons.demo";
import * as d57 from "@properui/ui/components/base/buttons/button-utility.demo";
import * as d58 from "@properui/ui/components/base/buttons/buttons.demo";
import * as d59 from "@properui/ui/components/base/buttons/social-buttons.demo";
import * as d60 from "@properui/ui/components/base/checkbox/checkbox.demo";
import * as d61 from "@properui/ui/components/base/dropdown/context-menus.demo";
import * as d62 from "@properui/ui/components/base/dropdown/dropdown.demo";
import * as d63 from "@properui/ui/components/base/input/inputs.demo";
import * as d64 from "@properui/ui/components/base/input/pin-input.demo";
import * as d65 from "@properui/ui/components/base/popover/popover.demo";
import * as d66 from "@properui/ui/components/base/progress-indicators/progress-indicators.demo";
import * as d67 from "@properui/ui/components/base/radio-buttons/radio-buttons.demo";
import * as d68 from "@properui/ui/components/base/select/multi-select.demo";
import * as d69 from "@properui/ui/components/base/select/select.demo";
import * as d70 from "@properui/ui/components/base/skeleton/skeleton.demo";
import * as d71 from "@properui/ui/components/base/slider/slider.demo";
import * as d72 from "@properui/ui/components/base/tags/tags.demo";
import * as d73 from "@properui/ui/components/base/text-editor/text-editor.demo";
import * as d74 from "@properui/ui/components/base/textarea/textarea.demo";
import * as d75 from "@properui/ui/components/base/toggle-chip/toggle-chip.demo";
import * as d76 from "@properui/ui/components/base/toggle/toggle.demo";
import * as d77 from "@properui/ui/components/base/tooltip/tooltip.demo";
import * as d78 from "@properui/ui/components/base/video-player/video-player.demo";
import * as d79 from "@properui/ui/components/foundations/featured-icon/featured-icon.demo";
import * as d80 from "@properui/ui/components/foundations/rating/rating.demo";
import * as d81 from "@properui/ui/components/foundations/typography/typography.demo";
import * as d82 from "@properui/ui/components/marketing-examples/404-pages/404-pages.demo";
import * as d83 from "@properui/ui/components/marketing-examples/about-pages/about-pages.demo";
import * as d84 from "@properui/ui/components/marketing-examples/blog-pages/blog-pages.demo";
import * as d85 from "@properui/ui/components/marketing-examples/blog-post-pages/blog-post-pages.demo";
import * as d86 from "@properui/ui/components/marketing-examples/contact-pages/contact-pages.demo";
import * as d87 from "@properui/ui/components/marketing-examples/faq-pages/faq-pages.demo";
import * as d88 from "@properui/ui/components/marketing-examples/landing-pages/landing-pages.demo";
import * as d89 from "@properui/ui/components/marketing-examples/legal-pages/legal-pages.demo";
import * as d90 from "@properui/ui/components/marketing-examples/pricing-pages/pricing-pages.demo";
import * as d91 from "@properui/ui/components/marketing-examples/team-pages/team-pages.demo";
import * as d92 from "@properui/ui/components/marketing/banners/banners.demo";
import * as d93 from "@properui/ui/components/marketing/blog-sections/blog-sections.demo";
import * as d94 from "@properui/ui/components/marketing/careers-sections/careers-sections.demo";
import * as d95 from "@properui/ui/components/marketing/contact-sections/contact-sections.demo";
import * as d96 from "@properui/ui/components/marketing/content-rich-text-sections/content-rich-text-sections.demo";
import * as d97 from "@properui/ui/components/marketing/cta-sections/cta-sections.demo";
import * as d98 from "@properui/ui/components/marketing/faq-sections/faq-sections.demo";
import * as d99 from "@properui/ui/components/marketing/features-sections/features-sections.demo";
import * as d100 from "@properui/ui/components/marketing/footers/footers.demo";
import * as d101 from "@properui/ui/components/marketing/header-navigations/header-navigations.demo";
import * as d102 from "@properui/ui/components/marketing/header-sections/header-sections.demo";
import * as d103 from "@properui/ui/components/marketing/hero-header-sections/hero-header-sections.demo";
import * as d104 from "@properui/ui/components/marketing/metrics-sections/metrics-sections.demo";
import * as d105 from "@properui/ui/components/marketing/newsletter-cta-sections/newsletter-cta-sections.demo";
import * as d106 from "@properui/ui/components/marketing/pricing-sections/pricing-sections.demo";
import * as d107 from "@properui/ui/components/marketing/social-proof-sections/social-proof-sections.demo";
import * as d108 from "@properui/ui/components/marketing/team-sections/team-sections.demo";
import * as d109 from "@properui/ui/components/marketing/testimonial-sections/testimonial-sections.demo";
import * as d110 from "@properui/ui/components/shared-assets/credit-card/credit-card.demo";
import * as d111 from "@properui/ui/components/shared-assets/illustrations/illustrations.demo";
import * as d112 from "@properui/ui/components/shared-assets/qr-code/qr-code.demo";

export const demos: Record<string, ComponentType> = {
    "404-sections:Section404Example": d0.Section404Example as ComponentType,
    "dashboards-02:DashboardWithHeaderNavigationExample": d1.DashboardWithHeaderNavigationExample as ComponentType,
    "dashboards:DashboardWithSidebarNavigationExample": d2.DashboardWithSidebarNavigationExample as ComponentType,
    "email-templates:EmailTemplateExample": d3.EmailTemplateExample as ComponentType,
    "forgot-password-pages:ForgotPasswordPageExample": d4.ForgotPasswordPageExample as ComponentType,
    "informational-pages-02:InformationalPageWithHeaderNavigationExample": d5.InformationalPageWithHeaderNavigationExample as ComponentType,
    "informational-pages:InformationalPageWithSidebarNavigationExample": d6.InformationalPageWithSidebarNavigationExample as ComponentType,
    "log-in-pages:LogInPageExample": d7.LogInPageExample as ComponentType,
    "settings-pages-02:SettingsPageWithHeaderNavigationExample": d8.SettingsPageWithHeaderNavigationExample as ComponentType,
    "settings-pages:SettingsPageWithSidebarNavigationExample": d9.SettingsPageWithSidebarNavigationExample as ComponentType,
    "sign-up-pages:SignUpPageExample": d10.SignUpPageExample as ComponentType,
    "verification-pages:VerificationPageExample": d11.VerificationPageExample as ComponentType,
    "activity-feed:ActivityFeedExample": d12.ActivityFeedExample as ComponentType,
    "activity-feed:ActivityFeedDivided": d12.ActivityFeedDivided as ComponentType,
    "activity-feed:ActivityFeedConnected": d12.ActivityFeedConnected as ComponentType,
    "activity-feed:ActivityFeedSpaced": d12.ActivityFeedSpaced as ComponentType,
    "activity-feed:MessagesDivided": d12.MessagesDivided as ComponentType,
    "activity-feed:MessagesConnected": d12.MessagesConnected as ComponentType,
    "activity-feed:MessagesSpaced": d12.MessagesSpaced as ComponentType,
    "alerts:AlertExample": d13.AlertExample as ComponentType,
    "alerts:FloatingDefault": d13.FloatingDefault as ComponentType,
    "alerts:FloatingBrand": d13.FloatingBrand as ComponentType,
    "alerts:FloatingGray": d13.FloatingGray as ComponentType,
    "alerts:FloatingError": d13.FloatingError as ComponentType,
    "alerts:FloatingWarning": d13.FloatingWarning as ComponentType,
    "alerts:FloatingSuccess": d13.FloatingSuccess as ComponentType,
    "alerts:FullWidthDefault": d13.FullWidthDefault as ComponentType,
    "alerts:FullWidthBrand": d13.FullWidthBrand as ComponentType,
    "alerts:FullWidthGray": d13.FullWidthGray as ComponentType,
    "alerts:FullWidthError": d13.FullWidthError as ComponentType,
    "alerts:FullWidthWarning": d13.FullWidthWarning as ComponentType,
    "alerts:FullWidthSuccess": d13.FullWidthSuccess as ComponentType,
    "header-navigation:HeaderNavigationExample": d14.HeaderNavigationExample as ComponentType,
    "header-navigation:Simple": d14.Simple as ComponentType,
    "header-navigation:DualTier": d14.DualTier as ComponentType,
    "sidebar-navigation:SidebarNavigationExample": d15.SidebarNavigationExample as ComponentType,
    "sidebar-navigation:Simple": d15.Simple as ComponentType,
    "sidebar-navigation:CustomBrand": d15.CustomBrand as ComponentType,
    "sidebar-navigation:DualTier": d15.DualTier as ComponentType,
    "sidebar-navigation:Slim": d15.Slim as ComponentType,
    "sidebar-navigation:SectionsDividers": d15.SectionsDividers as ComponentType,
    "sidebar-navigation:SectionsSubheadings": d15.SectionsSubheadings as ComponentType,
    "sidebar-navigation:ProgressBar": d15.ProgressBar as ComponentType,
    "sidebar-navigation:ProgressCircle": d15.ProgressCircle as ComponentType,
    "sidebar-navigation:Image": d15.Image as ComponentType,
    "sidebar-navigation:CookiePreferences": d15.CookiePreferences as ComponentType,
    "sidebar-navigation:ReferralLink": d15.ReferralLink as ComponentType,
    "sidebar-navigation:OnboardingSteps": d15.OnboardingSteps as ComponentType,
    "sidebar-navigation:UpgradeCTA": d15.UpgradeCTA as ComponentType,
    "sidebar-navigation:SupportCTA": d15.SupportCTA as ComponentType,
    "sidebar-navigation:EventCTA": d15.EventCTA as ComponentType,
    "sidebar-navigation:Message": d15.Message as ComponentType,
    "sidebar-navigation:CurrentProjects": d15.CurrentProjects as ComponentType,
    "sidebar-navigation:FreeTrialCTA": d15.FreeTrialCTA as ComponentType,
    "sidebar-navigation:QRCode": d15.QRCode as ComponentType,
    "breadcrumbs:BreadcrumbsExample": d16.BreadcrumbsExample as ComponentType,
    "breadcrumbs:BreadcrumbsText": d16.BreadcrumbsText as ComponentType,
    "breadcrumbs:BreadcrumbsTextWithLine": d16.BreadcrumbsTextWithLine as ComponentType,
    "breadcrumbs:BreadcrumbsButton": d16.BreadcrumbsButton as ComponentType,
    "breadcrumbs:AccountButtonChevron": d16.AccountButtonChevron as ComponentType,
    "breadcrumbs:AccountButtonSlash": d16.AccountButtonSlash as ComponentType,
    "callout:CalloutExample": d17.CalloutExample as ComponentType,
    "callout:Tones": d17.Tones as ComponentType,
    "callout:WithoutTitle": d17.WithoutTitle as ComponentType,
    "callout:WithoutIcon": d17.WithoutIcon as ComponentType,
    "card-headers:CardHeaderExample": d18.CardHeaderExample as ComponentType,
    "card-headers:CardHeaderWithBadge": d18.CardHeaderWithBadge as ComponentType,
    "card-headers:CardHeaderWithAvatarAndBadge": d18.CardHeaderWithAvatarAndBadge as ComponentType,
    "carousel:CarouselExample": d19.CarouselExample as ComponentType,
    "carousel:CarouselMd": d19.CarouselMd as ComponentType,
    "carousel:CarouselLg": d19.CarouselLg as ComponentType,
    "activity-gauges:ActivityGaugeXs": d20.ActivityGaugeXs as ComponentType,
    "activity-gauges:ActivityGaugeSm": d20.ActivityGaugeSm as ComponentType,
    "activity-gauges:ActivityGaugeMd": d20.ActivityGaugeMd as ComponentType,
    "activity-gauges:ActivityGaugeLg": d20.ActivityGaugeLg as ComponentType,
    "activity-gauges:ActivityGaugeExample": d20.ActivityGaugeExample as ComponentType,
    "line-bar-charts:LineChart01": d21.LineChart01 as ComponentType,
    "line-bar-charts:LineChart02": d21.LineChart02 as ComponentType,
    "line-bar-charts:LineChart03": d21.LineChart03 as ComponentType,
    "line-bar-charts:LineChart04": d21.LineChart04 as ComponentType,
    "line-bar-charts:BarChart01": d21.BarChart01 as ComponentType,
    "line-bar-charts:BarChart02": d21.BarChart02 as ComponentType,
    "line-bar-charts:BarChart03": d21.BarChart03 as ComponentType,
    "line-bar-charts:LineChartExample": d21.LineChartExample as ComponentType,
    "pie-charts:PieChartXxl": d22.PieChartXxl as ComponentType,
    "pie-charts:PieChartXs": d22.PieChartXs as ComponentType,
    "pie-charts:PieChartSm": d22.PieChartSm as ComponentType,
    "pie-charts:PieChartMd": d22.PieChartMd as ComponentType,
    "pie-charts:PieChartLg": d22.PieChartLg as ComponentType,
    "pie-charts:PieChartExample": d22.PieChartExample as ComponentType,
    "radar-charts:RadarChart": d23.RadarChart as ComponentType,
    "radar-charts:RadarChartExample": d23.RadarChartExample as ComponentType,
    "code-snippet:CodeSnippetExample": d24.CodeSnippetExample as ComponentType,
    "code-snippet:WithLineNumber": d24.WithLineNumber as ComponentType,
    "code-snippet:WithoutLineNumber": d24.WithoutLineNumber as ComponentType,
    "code-snippet:ShowMore": d24.ShowMore as ComponentType,
    "code-snippet:WithTabs": d24.WithTabs as ComponentType,
    "color-picker:ColorPickerExample": d25.ColorPickerExample as ComponentType,
    "color-picker:ColorPicker": d25.ColorPicker as ComponentType,
    "color-picker:ColorSwatchPicker": d25.ColorSwatchPicker as ComponentType,
    "color-picker:SavedSwatchesSmall": d25.SavedSwatchesSmall as ComponentType,
    "color-picker:SavedSwatchesMedium": d25.SavedSwatchesMedium as ComponentType,
    "color-picker:BrandSwatches": d25.BrandSwatches as ComponentType,
    "color-picker:GraySwatches": d25.GraySwatches as ComponentType,
    "color-picker:MinimalPicker": d25.MinimalPicker as ComponentType,
    "color-picker:HueSlider": d25.HueSlider as ComponentType,
    "color-picker:TransparencySlider": d25.TransparencySlider as ComponentType,
    "color-picker:PalettePicker": d25.PalettePicker as ComponentType,
    "command-menu:CommandMenuExample": d26.CommandMenuExample as ComponentType,
    "command-menu:Users": d26.Users as ComponentType,
    "command-menu:UsersStacked": d26.UsersStacked as ComponentType,
    "command-menu:Actions": d26.Actions as ComponentType,
    "command-menu:ActionsStacked": d26.ActionsStacked as ComponentType,
    "command-menu:EmptyState": d26.EmptyState as ComponentType,
    "command-menu:UsersMenu": d26.UsersMenu as ComponentType,
    "command-menu:UsersMenuStacked": d26.UsersMenuStacked as ComponentType,
    "command-menu:IntegrationsMenu": d26.IntegrationsMenu as ComponentType,
    "command-menu:IntegrationsMenuStacked": d26.IntegrationsMenuStacked as ComponentType,
    "confirm-dialog:ConfirmDialogExample": d27.ConfirmDialogExample as ComponentType,
    "confirm-dialog:Destructive": d27.Destructive as ComponentType,
    "confirm-dialog:AsyncConfirm": d27.AsyncConfirm as ComponentType,
    "content-divider:ContentDividerExample": d28.ContentDividerExample as ComponentType,
    "content-divider:SingleLine": d28.SingleLine as ComponentType,
    "content-divider:DualLine": d28.DualLine as ComponentType,
    "content-divider:BackgroundFill": d28.BackgroundFill as ComponentType,
    "calendar:CalendarExample": d29.CalendarExample as ComponentType,
    "calendar:CalendarMonthView": d29.CalendarMonthView as ComponentType,
    "calendar:CalendarWeekView": d29.CalendarWeekView as ComponentType,
    "calendar:CalendarDayView": d29.CalendarDayView as ComponentType,
    "date-pickers:DatePickerExample": d30.DatePickerExample as ComponentType,
    "date-pickers:DatePicker": d30.DatePicker as ComponentType,
    "date-pickers:DateTimePicker": d30.DateTimePicker as ComponentType,
    "date-pickers:DateRangePickerWithPresets": d30.DateRangePickerWithPresets as ComponentType,
    "date-pickers:Calendar": d30.Calendar as ComponentType,
    "date-pickers:CalendarCard": d30.CalendarCard as ComponentType,
    "date-pickers:RangeCalendar": d30.RangeCalendar as ComponentType,
    "date-pickers:RangeCalendarCard": d30.RangeCalendarCard as ComponentType,
    "description-list:DescriptionListExample": d31.DescriptionListExample as ComponentType,
    "description-list:Horizontal": d31.Horizontal as ComponentType,
    "description-list:Stacked": d31.Stacked as ComponentType,
    "empty-state:EmptyStateExample": d32.EmptyStateExample as ComponentType,
    "empty-state:FeaturedIcon": d32.FeaturedIcon as ComponentType,
    "empty-state:Illustration": d32.Illustration as ComponentType,
    "empty-state:FileIcon": d32.FileIcon as ComponentType,
    "empty-state:AvatarRadius": d32.AvatarRadius as ComponentType,
    "empty-state:AvatarRow": d32.AvatarRow as ComponentType,
    "empty-state:AvatarGrid": d32.AvatarGrid as ComponentType,
    "file-upload:FileUploadExample": d33.FileUploadExample as ComponentType,
    "file-upload:ProgressBar": d33.ProgressBar as ComponentType,
    "file-upload:ProgressFill": d33.ProgressFill as ComponentType,
    "file-upload:Disabled": d33.Disabled as ComponentType,
    "file-upload:AcceptImageOnly": d33.AcceptImageOnly as ComponentType,
    "file-upload:MaxSizeLimit": d33.MaxSizeLimit as ComponentType,
    "filter-bars:FilterBarExample": d34.FilterBarExample as ComponentType,
    "filter-bars:Simple": d34.Simple as ComponentType,
    "filter-bars:TabsAndSearch": d34.TabsAndSearch as ComponentType,
    "filter-bars:TabsAndDatePicker": d34.TabsAndDatePicker as ComponentType,
    "filter-bars:DateFilters": d34.DateFilters as ComponentType,
    "filter-bars:Dropdowns": d34.Dropdowns as ComponentType,
    "filter-bars:DropdownsAndDatePicker": d34.DropdownsAndDatePicker as ComponentType,
    "filter-bars:AdvancedFilterInactive": d34.AdvancedFilterInactive as ComponentType,
    "filter-bars:AdvancedFilterActive": d34.AdvancedFilterActive as ComponentType,
    "filter-bars:FilterDropdownEmptyState": d34.FilterDropdownEmptyState as ComponentType,
    "filter-bars:FilterDropdownInactive": d34.FilterDropdownInactive as ComponentType,
    "filter-bars:FilterDropdownActive": d34.FilterDropdownActive as ComponentType,
    "filter-bars:FiltersAdvancedEmptyStateMenu": d34.FiltersAdvancedEmptyStateMenu as ComponentType,
    "filter-bars:FiltersAdvancedActiveMenu": d34.FiltersAdvancedActiveMenu as ComponentType,
    "gradient-picker:GradientPickerExample": d35.GradientPickerExample as ComponentType,
    "gradient-picker:GradientPicker": d35.GradientPicker as ComponentType,
    "image-picker:ImagePickerExample": d36.ImagePickerExample as ComponentType,
    "image-picker:ImagePicker": d36.ImagePicker as ComponentType,
    "inline-cta:InlineCTAExample": d37.InlineCTAExample as ComponentType,
    "inline-cta:Actions": d37.Actions as ComponentType,
    "inline-cta:EmailField": d37.EmailField as ComponentType,
    "inline-cta:ChangePlan": d37.ChangePlan as ComponentType,
    "inline-cta:UpgradePlan": d37.UpgradePlan as ComponentType,
    "inline-cta:PaymentMethod": d37.PaymentMethod as ComponentType,
    "inline-cta:Receipt": d37.Receipt as ComponentType,
    "loading-indicator:LoadingIndicatorExample": d38.LoadingIndicatorExample as ComponentType,
    "loading-indicator:LineSimple": d38.LineSimple as ComponentType,
    "loading-indicator:LineSimpleWithLabel": d38.LineSimpleWithLabel as ComponentType,
    "loading-indicator:LineSpinner": d38.LineSpinner as ComponentType,
    "loading-indicator:LineSpinnerWithLabel": d38.LineSpinnerWithLabel as ComponentType,
    "loading-indicator:DotCircle": d38.DotCircle as ComponentType,
    "loading-indicator:DotCircleWithLabel": d38.DotCircleWithLabel as ComponentType,
    "loading-indicator:Sizes": d38.Sizes as ComponentType,
    "loading-indicator:InlineXs": d38.InlineXs as ComponentType,
    "messaging:MessagingExample": d39.MessagingExample as ComponentType,
    "messaging:MessageStatus": d39.MessageStatus as ComponentType,
    "messaging:MessageActionMinimal": d39.MessageActionMinimal as ComponentType,
    "messaging:MessageActionTextarea": d39.MessageActionTextarea as ComponentType,
    "messaging:MessageActionAdvanced": d39.MessageActionAdvanced as ComponentType,
    "messaging:MessageSimple": d39.MessageSimple as ComponentType,
    "messaging:MessageReactions": d39.MessageReactions as ComponentType,
    "messaging:MessageReply": d39.MessageReply as ComponentType,
    "messaging:MessageAttachment": d39.MessageAttachment as ComponentType,
    "messaging:MessageAudio": d39.MessageAudio as ComponentType,
    "messaging:MessageImage": d39.MessageImage as ComponentType,
    "messaging:MessageLinkPreview": d39.MessageLinkPreview as ComponentType,
    "messaging:MessageLinkMinimal": d39.MessageLinkMinimal as ComponentType,
    "messaging:MessageWriting": d39.MessageWriting as ComponentType,
    "metrics:MetricsExample": d40.MetricsExample as ComponentType,
    "metrics:Simple": d40.Simple as ComponentType,
    "metrics:SimpleNoChange": d40.SimpleNoChange as ComponentType,
    "metrics:SimpleActions": d40.SimpleActions as ComponentType,
    "metrics:MetricsIcon01": d40.MetricsIcon01 as ComponentType,
    "metrics:MetricsIconActions01": d40.MetricsIconActions01 as ComponentType,
    "metrics:MetricsIcon02": d40.MetricsIcon02 as ComponentType,
    "metrics:MetricsIconActions02": d40.MetricsIconActions02 as ComponentType,
    "metrics:MetricsIcon03": d40.MetricsIcon03 as ComponentType,
    "metrics:MetricsIconActions03": d40.MetricsIconActions03 as ComponentType,
    "metrics:MetricsIcon04": d40.MetricsIcon04 as ComponentType,
    "metrics:MetricsIconActions04": d40.MetricsIconActions04 as ComponentType,
    "metrics:Chart01": d40.Chart01 as ComponentType,
    "metrics:ChartActions01": d40.ChartActions01 as ComponentType,
    "metrics:Chart02": d40.Chart02 as ComponentType,
    "metrics:ChartActions02": d40.ChartActions02 as ComponentType,
    "metrics:Chart03": d40.Chart03 as ComponentType,
    "metrics:ChartActions03": d40.ChartActions03 as ComponentType,
    "metrics:Chart04": d40.Chart04 as ComponentType,
    "metrics:ChartActions04": d40.ChartActions04 as ComponentType,
    "modals:ModalExample": d41.ModalExample as ComponentType,
    "modals:StackedLeftAligned": d41.StackedLeftAligned as ComponentType,
    "modals:WarningStackedLeftAligned": d41.WarningStackedLeftAligned as ComponentType,
    "modals:DestructiveStackedLeftAligned": d41.DestructiveStackedLeftAligned as ComponentType,
    "modals:ConfirmDialog": d41.ConfirmDialog as ComponentType,
    "modals:Horizontal": d41.Horizontal as ComponentType,
    "modals:WarningHorizontal": d41.WarningHorizontal as ComponentType,
    "modals:DestructiveHorizontal": d41.DestructiveHorizontal as ComponentType,
    "modals:Login": d41.Login as ComponentType,
    "modals:Signup01": d41.Signup01 as ComponentType,
    "modals:Signup02": d41.Signup02 as ComponentType,
    "modals:Checkboxes": d41.Checkboxes as ComponentType,
    "modals:Toggles": d41.Toggles as ComponentType,
    "modals:LinkField": d41.LinkField as ComponentType,
    "modals:Dropdown": d41.Dropdown as ComponentType,
    "modals:InputField": d41.InputField as ComponentType,
    "modals:Labels": d41.Labels as ComponentType,
    "modals:AccessRequest": d41.AccessRequest as ComponentType,
    "modals:EmailInvite": d41.EmailInvite as ComponentType,
    "modals:UserInvite": d41.UserInvite as ComponentType,
    "modals:StackedWithTeam": d41.StackedWithTeam as ComponentType,
    "modals:StackedWithTeamAndLink": d41.StackedWithTeamAndLink as ComponentType,
    "modals:StackedWithTeamAndInvites": d41.StackedWithTeamAndInvites as ComponentType,
    "modals:VerificationCode": d41.VerificationCode as ComponentType,
    "modals:TwoFactorCode": d41.TwoFactorCode as ComponentType,
    "modals:PasswordPrompt": d41.PasswordPrompt as ComponentType,
    "modals:CenteredPhoto": d41.CenteredPhoto as ComponentType,
    "modals:CenteredPhotoCarousel": d41.CenteredPhotoCarousel as ComponentType,
    "modals:CenteredVideoCarousel": d41.CenteredVideoCarousel as ComponentType,
    "modals:PaymentDetails": d41.PaymentDetails as ComponentType,
    "modals:PaymentDetailsWithImage": d41.PaymentDetailsWithImage as ComponentType,
    "modals:Plan01": d41.Plan01 as ComponentType,
    "modals:Plan02": d41.Plan02 as ComponentType,
    "modals:PaymentMethod": d41.PaymentMethod as ComponentType,
    "modals:DatePicker": d41.DatePicker as ComponentType,
    "modals:FileUpload": d41.FileUpload as ComponentType,
    "modals:ProfileSettings": d41.ProfileSettings as ComponentType,
    "modals:UserSelection": d41.UserSelection as ComponentType,
    "modals:Form01": d41.Form01 as ComponentType,
    "modals:Form02": d41.Form02 as ComponentType,
    "modals:ImageCrop": d41.ImageCrop as ComponentType,
    "modals:CalendarEvent": d41.CalendarEvent as ComponentType,
    "modals:BannerAppearance": d41.BannerAppearance as ComponentType,
    "modals:AppearanceSettings": d41.AppearanceSettings as ComponentType,
    "modals:AIAssistant": d41.AIAssistant as ComponentType,
    "modals:UserSettings": d41.UserSettings as ComponentType,
    "modals:NewProject": d41.NewProject as ComponentType,
    "modals:TextEditor": d41.TextEditor as ComponentType,
    "modals:ShareProject": d41.ShareProject as ComponentType,
    "modals:CreateEvent": d41.CreateEvent as ComponentType,
    "modals:Integration": d41.Integration as ComponentType,
    "modals:NewMessageEmptyState": d41.NewMessageEmptyState as ComponentType,
    "modals:NewMessageFilled": d41.NewMessageFilled as ComponentType,
    "notifications:NotificationExample": d42.NotificationExample as ComponentType,
    "notifications:IconDefault": d42.IconDefault as ComponentType,
    "notifications:IconGray": d42.IconGray as ComponentType,
    "notifications:IconBrand": d42.IconBrand as ComponentType,
    "notifications:IconError": d42.IconError as ComponentType,
    "notifications:IconWarning": d42.IconWarning as ComponentType,
    "notifications:IconSuccess": d42.IconSuccess as ComponentType,
    "notifications:ProgressNotification": d42.ProgressNotification as ComponentType,
    "notifications:ImageNotification": d42.ImageNotification as ComponentType,
    "notifications:AvatarNotification": d42.AvatarNotification as ComponentType,
    "page-headers:PageHeaderExample": d43.PageHeaderExample as ComponentType,
    "page-headers:Simple": d43.Simple as ComponentType,
    "page-headers:Avatar": d43.Avatar as ComponentType,
    "page-headers:BannerSimple": d43.BannerSimple as ComponentType,
    "page-headers:BannerAvatar": d43.BannerAvatar as ComponentType,
    "page-headers:BannerSimpleCentered": d43.BannerSimpleCentered as ComponentType,
    "page-headers:BannerAvatarCentered": d43.BannerAvatarCentered as ComponentType,
    "pagination:PaginationExample": d44.PaginationExample as ComponentType,
    "pagination:PageDefault": d44.PageDefault as ComponentType,
    "pagination:PageMinimalCenter": d44.PageMinimalCenter as ComponentType,
    "pagination:CardDefault": d44.CardDefault as ComponentType,
    "pagination:CardMinimalRightAligned": d44.CardMinimalRightAligned as ComponentType,
    "pagination:CardMinimalCenterAligned": d44.CardMinimalCenterAligned as ComponentType,
    "pagination:CardMinimalLeftAligned": d44.CardMinimalLeftAligned as ComponentType,
    "pagination:ButtonGroupRightAligned": d44.ButtonGroupRightAligned as ComponentType,
    "pagination:ButtonGroupCenterAligned": d44.ButtonGroupCenterAligned as ComponentType,
    "pagination:ButtonGroupLeftAligned": d44.ButtonGroupLeftAligned as ComponentType,
    "pagination:CardAdvanced": d44.CardAdvanced as ComponentType,
    "pagination:CardAdvancedCenter": d44.CardAdvancedCenter as ComponentType,
    "pagination:PaginationDot": d44.PaginationDot as ComponentType,
    "pagination:Cursor": d44.Cursor as ComponentType,
    "pagination:PaginationLine": d44.PaginationLine as ComponentType,
    "progress-steps:ProgressStepsExample": d45.ProgressStepsExample as ComponentType,
    "progress-steps:IconCentered": d45.IconCentered as ComponentType,
    "progress-steps:IconCenteredWithNumber": d45.IconCenteredWithNumber as ComponentType,
    "progress-steps:FeaturedIconCentered": d45.FeaturedIconCentered as ComponentType,
    "progress-steps:IconWithText": d45.IconWithText as ComponentType,
    "progress-steps:IconWithNumber": d45.IconWithNumber as ComponentType,
    "progress-steps:FeaturedIconWithText": d45.FeaturedIconWithText as ComponentType,
    "progress-steps:MinimalIcons": d45.MinimalIcons as ComponentType,
    "progress-steps:MinimalIconsConnected": d45.MinimalIconsConnected as ComponentType,
    "progress-steps:Interactive": d45.Interactive as ComponentType,
    "progress-steps:WithStepContent": d45.WithStepContent as ComponentType,
    "progress-steps:TextWithLine": d45.TextWithLine as ComponentType,
    "section-footers:SectionFooterExample": d46.SectionFooterExample as ComponentType,
    "section-footers:SectionFooterButtonGroup": d46.SectionFooterButtonGroup as ComponentType,
    "section-footers:SectionFooter": d46.SectionFooter as ComponentType,
    "section-footers:SectionFooterCardButtonGroup": d46.SectionFooterCardButtonGroup as ComponentType,
    "section-footers:SectionFooterCard": d46.SectionFooterCard as ComponentType,
    "section-headers:SectionHeaderExample": d47.SectionHeaderExample as ComponentType,
    "section-headers:SectionHeaderButtons": d47.SectionHeaderButtons as ComponentType,
    "section-headers:SectionHeaderSearchInput": d47.SectionHeaderSearchInput as ComponentType,
    "section-headers:SectionHeaderButtonGroup": d47.SectionHeaderButtonGroup as ComponentType,
    "section-headers:SectionHeaderButtonsWithTabs": d47.SectionHeaderButtonsWithTabs as ComponentType,
    "section-headers:SectionHeaderSearchInputWithTabs": d47.SectionHeaderSearchInputWithTabs as ComponentType,
    "section-headers:SectionHeaderButtonGroupsWithTabs": d47.SectionHeaderButtonGroupsWithTabs as ComponentType,
    "slideout-menus:DrawerExample": d48.DrawerExample as ComponentType,
    "slideout-menus:PlaceholderMenu": d48.PlaceholderMenu as ComponentType,
    "slideout-menus:UserProfileMenu": d48.UserProfileMenu as ComponentType,
    "slideout-menus:MessagesMenu": d48.MessagesMenu as ComponentType,
    "slideout-menus:MessageChatMenu": d48.MessageChatMenu as ComponentType,
    "slideout-menus:PaymentMethodMenu": d48.PaymentMethodMenu as ComponentType,
    "slideout-menus:PaymentDetailsMenu": d48.PaymentDetailsMenu as ComponentType,
    "slideout-menus:PlanMenu": d48.PlanMenu as ComponentType,
    "slideout-menus:TeamMembersMenu": d48.TeamMembersMenu as ComponentType,
    "slideout-menus:FiltersMenu": d48.FiltersMenu as ComponentType,
    "slideout-menus:FiltersAdvancedEmptyStateMenu": d48.FiltersAdvancedEmptyStateMenu as ComponentType,
    "slideout-menus:FiltersAdvancedActiveMenu": d48.FiltersAdvancedActiveMenu as ComponentType,
    "slideout-menus:FileUploadMenu": d48.FileUploadMenu as ComponentType,
    "slideout-menus:LabelsMenu": d48.LabelsMenu as ComponentType,
    "slideout-menus:ProjectDetailsMenu": d48.ProjectDetailsMenu as ComponentType,
    "slideout-menus:NotificationSettingsCheckboxMenu": d48.NotificationSettingsCheckboxMenu as ComponentType,
    "slideout-menus:NotificationSettingsButtonMenu": d48.NotificationSettingsButtonMenu as ComponentType,
    "slideout-menus:NotificationsMenu": d48.NotificationsMenu as ComponentType,
    "slideout-menus:OrderSummaryMenu": d48.OrderSummaryMenu as ComponentType,
    "slideout-menus:CalendarEventMenu": d48.CalendarEventMenu as ComponentType,
    "slideout-menus:UserSettingsMenu": d48.UserSettingsMenu as ComponentType,
    "slideout-menus:AIAssistantMenu": d48.AIAssistantMenu as ComponentType,
    "slideout-menus:AIAssistantMessageMenu": d48.AIAssistantMessageMenu as ComponentType,
    "slideout-menus:ShareProjectMenu": d48.ShareProjectMenu as ComponentType,
    "slideout-menus:CreateEventMenu": d48.CreateEventMenu as ComponentType,
    "slideout-menus:IntegrationMenu": d48.IntegrationMenu as ComponentType,
    "table:TableExample": d49.TableExample as ComponentType,
    "table:TableSmallSizeExample": d49.TableSmallSizeExample as ComponentType,
    "table:DividerLine01": d49.DividerLine01 as ComponentType,
    "table:AlternatingFills01": d49.AlternatingFills01 as ComponentType,
    "table:DividerLine02": d49.DividerLine02 as ComponentType,
    "table:AlternatingFills02": d49.AlternatingFills02 as ComponentType,
    "table:DividerLine03": d49.DividerLine03 as ComponentType,
    "table:AlternatingFills03": d49.AlternatingFills03 as ComponentType,
    "table:DividerLine04": d49.DividerLine04 as ComponentType,
    "table:AlternatingFills04": d49.AlternatingFills04 as ComponentType,
    "table:StaticUsage": d49.StaticUsage as ComponentType,
    "table:VisuallyHiddenColumnLabel": d49.VisuallyHiddenColumnLabel as ComponentType,
    "table:NoVendorsFound": d49.NoVendorsFound as ComponentType,
    "table:SomethingWentWrong": d49.SomethingWentWrong as ComponentType,
    "table:NoUsersFound": d49.NoUsersFound as ComponentType,
    "table:AddFirstIntegration": d49.AddFirstIntegration as ComponentType,
    "table:InviteFirstUser": d49.InviteFirstUser as ComponentType,
    "table:OfflineState": d49.OfflineState as ComponentType,
    "tabs:TabsExample": d50.TabsExample as ComponentType,
    "tabs:ButtonBrandHorizontal": d50.ButtonBrandHorizontal as ComponentType,
    "tabs:ButtonGrayHorizontal": d50.ButtonGrayHorizontal as ComponentType,
    "tabs:ButtonBorderHorizontal": d50.ButtonBorderHorizontal as ComponentType,
    "tabs:ButtonMinimalHorizontal": d50.ButtonMinimalHorizontal as ComponentType,
    "tabs:Underline": d50.Underline as ComponentType,
    "tabs:ButtonBrandVertical": d50.ButtonBrandVertical as ComponentType,
    "tabs:ButtonGrayVertical": d50.ButtonGrayVertical as ComponentType,
    "tabs:ButtonBorderVertical": d50.ButtonBorderVertical as ComponentType,
    "tabs:ButtonMinimalVertical": d50.ButtonMinimalVertical as ComponentType,
    "tabs:Line": d50.Line as ComponentType,
    "tree-view:TreeViewExample": d51.TreeViewExample as ComponentType,
    "tree-view:SimpleSm": d51.SimpleSm as ComponentType,
    "tree-view:SimpleMd": d51.SimpleMd as ComponentType,
    "tree-view:AdvancedSm": d51.AdvancedSm as ComponentType,
    "tree-view:AdvancedMd": d51.AdvancedMd as ComponentType,
    "avatar:AvatarExample": d52.AvatarExample as ComponentType,
    "avatar:Avatar": d52.Avatar as ComponentType,
    "avatar:BorderExample": d52.BorderExample as ComponentType,
    "avatar:StatusIndicatorExample": d52.StatusIndicatorExample as ComponentType,
    "avatar:CompanyLogoExample": d52.CompanyLogoExample as ComponentType,
    "avatar:VerifiedBadgeExample": d52.VerifiedBadgeExample as ComponentType,
    "avatar:PlaceholderExample": d52.PlaceholderExample as ComponentType,
    "avatar:InitialsExample": d52.InitialsExample as ComponentType,
    "avatar:LabelGroupExample": d52.LabelGroupExample as ComponentType,
    "avatar:GroupExample": d52.GroupExample as ComponentType,
    "avatar:ProfilePhoto": d52.ProfilePhoto as ComponentType,
    "avatar:ProfilePhotoPlaceholderExample": d52.ProfilePhotoPlaceholderExample as ComponentType,
    "avatar:ProfilePhotoInitialsExample": d52.ProfilePhotoInitialsExample as ComponentType,
    "badge-groups:BadgeGroupExample": d53.BadgeGroupExample as ComponentType,
    "badge-groups:PillColorLeadingGray": d53.PillColorLeadingGray as ComponentType,
    "badge-groups:PillColorLeadingBrand": d53.PillColorLeadingBrand as ComponentType,
    "badge-groups:PillColorLeadingError": d53.PillColorLeadingError as ComponentType,
    "badge-groups:PillColorLeadingWarning": d53.PillColorLeadingWarning as ComponentType,
    "badge-groups:PillColorLeadingSuccess": d53.PillColorLeadingSuccess as ComponentType,
    "badge-groups:PillColorTrailingGray": d53.PillColorTrailingGray as ComponentType,
    "badge-groups:PillColorTrailingBrand": d53.PillColorTrailingBrand as ComponentType,
    "badge-groups:PillColorTrailingError": d53.PillColorTrailingError as ComponentType,
    "badge-groups:PillColorTrailingWarning": d53.PillColorTrailingWarning as ComponentType,
    "badge-groups:PillColorTrailingSuccess": d53.PillColorTrailingSuccess as ComponentType,
    "badge-groups:ModernLeadingGray": d53.ModernLeadingGray as ComponentType,
    "badge-groups:ModernLeadingBrand": d53.ModernLeadingBrand as ComponentType,
    "badge-groups:ModernLeadingError": d53.ModernLeadingError as ComponentType,
    "badge-groups:ModernLeadingWarning": d53.ModernLeadingWarning as ComponentType,
    "badge-groups:ModernLeadingSuccess": d53.ModernLeadingSuccess as ComponentType,
    "badge-groups:ModernTrailingGray": d53.ModernTrailingGray as ComponentType,
    "badge-groups:ModernTrailingBrand": d53.ModernTrailingBrand as ComponentType,
    "badge-groups:ModernTrailingError": d53.ModernTrailingError as ComponentType,
    "badge-groups:ModernTrailingWarning": d53.ModernTrailingWarning as ComponentType,
    "badge-groups:ModernTrailingSuccess": d53.ModernTrailingSuccess as ComponentType,
    "badges:BadgeExample": d54.BadgeExample as ComponentType,
    "badges:PillColor": d54.PillColor as ComponentType,
    "badges:Color": d54.Color as ComponentType,
    "badges:Modern": d54.Modern as ComponentType,
    "badges:WithDot": d54.WithDot as ComponentType,
    "badges:WithDotBadgeColor": d54.WithDotBadgeColor as ComponentType,
    "badges:WithDotBadgeModern": d54.WithDotBadgeModern as ComponentType,
    "badges:WithFlag": d54.WithFlag as ComponentType,
    "badges:WithFlagBadgeColor": d54.WithFlagBadgeColor as ComponentType,
    "badges:WithFlagBadgeModern": d54.WithFlagBadgeModern as ComponentType,
    "badges:WithAvatar": d54.WithAvatar as ComponentType,
    "badges:WithAvatarBadgeColor": d54.WithAvatarBadgeColor as ComponentType,
    "badges:WithAvatarBadgeModern": d54.WithAvatarBadgeModern as ComponentType,
    "badges:WithCloseX": d54.WithCloseX as ComponentType,
    "badges:WithCloseXBadgeColor": d54.WithCloseXBadgeColor as ComponentType,
    "badges:WithCloseXBadgeModern": d54.WithCloseXBadgeModern as ComponentType,
    "badges:WithIconLeading": d54.WithIconLeading as ComponentType,
    "badges:ColorWithIconLeading": d54.ColorWithIconLeading as ComponentType,
    "badges:ModernWithIconLeading": d54.ModernWithIconLeading as ComponentType,
    "badges:WithIconTrailing": d54.WithIconTrailing as ComponentType,
    "badges:ColorWithIconTrailing": d54.ColorWithIconTrailing as ComponentType,
    "badges:ModernWithIconTrailing": d54.ModernWithIconTrailing as ComponentType,
    "badges:WithIconOnly": d54.WithIconOnly as ComponentType,
    "badges:ColorWithIconOnly": d54.ColorWithIconOnly as ComponentType,
    "badges:ModernWithIconOnly": d54.ModernWithIconOnly as ComponentType,
    "button-group:ButtonGroupExample": d55.ButtonGroupExample as ComponentType,
    "button-group:LeadingIcon": d55.LeadingIcon as ComponentType,
    "button-group:WithDot": d55.WithDot as ComponentType,
    "button-group:Disabled": d55.Disabled as ComponentType,
    "button-group:DisabledIndividualItem": d55.DisabledIndividualItem as ComponentType,
    "button-group:Selection": d55.Selection as ComponentType,
    "button-group:MultipleSelection": d55.MultipleSelection as ComponentType,
    "app-store-buttons:MobileAppStoreButtonsExample": d56.MobileAppStoreButtonsExample as ComponentType,
    "app-store-buttons:GooglePlayButtons": d56.GooglePlayButtons as ComponentType,
    "app-store-buttons:AppStoreButtons": d56.AppStoreButtons as ComponentType,
    "app-store-buttons:GalaxyStoreButtons": d56.GalaxyStoreButtons as ComponentType,
    "app-store-buttons:AppGalleryButtons": d56.AppGalleryButtons as ComponentType,
    "app-store-buttons:GooglePlayOutlineButtons": d56.GooglePlayOutlineButtons as ComponentType,
    "app-store-buttons:AppStoreOutlineButtons": d56.AppStoreOutlineButtons as ComponentType,
    "app-store-buttons:GalaxyStoreOutlineButtons": d56.GalaxyStoreOutlineButtons as ComponentType,
    "app-store-buttons:AppGalleryOutlineButtons": d56.AppGalleryOutlineButtons as ComponentType,
    "button-utility:UtilityButtonsExample": d57.UtilityButtonsExample as ComponentType,
    "button-utility:Secondary": d57.Secondary as ComponentType,
    "button-utility:Tertiary": d57.Tertiary as ComponentType,
    "button-utility:Sizes": d57.Sizes as ComponentType,
    "button-utility:Disabled": d57.Disabled as ComponentType,
    "button-utility:CloseX": d57.CloseX as ComponentType,
    "button-utility:CloseXDark": d57.CloseXDark as ComponentType,
    "buttons:ButtonExample": d58.ButtonExample as ComponentType,
    "buttons:PrimaryButtons": d58.PrimaryButtons as ComponentType,
    "buttons:SecondaryButtons": d58.SecondaryButtons as ComponentType,
    "buttons:TertiaryButtons": d58.TertiaryButtons as ComponentType,
    "buttons:LinkColorButtonsExample": d58.LinkColorButtonsExample as ComponentType,
    "buttons:LinkGrayButtons": d58.LinkGrayButtons as ComponentType,
    "buttons:IconLeadingButtonsExample": d58.IconLeadingButtonsExample as ComponentType,
    "buttons:IconTrailingButtonsExample": d58.IconTrailingButtonsExample as ComponentType,
    "buttons:IconOnlyButtonsExample": d58.IconOnlyButtonsExample as ComponentType,
    "buttons:LoadingButtonsExample": d58.LoadingButtonsExample as ComponentType,
    "buttons:DisabledButtonsExample": d58.DisabledButtonsExample as ComponentType,
    "buttons:PrimaryButtonsDestructiveExample": d58.PrimaryButtonsDestructiveExample as ComponentType,
    "buttons:SecondaryButtonsDestructive": d58.SecondaryButtonsDestructive as ComponentType,
    "buttons:TertiaryButtonsDestructive": d58.TertiaryButtonsDestructive as ComponentType,
    "social-buttons:SocialButtonsExample": d59.SocialButtonsExample as ComponentType,
    "social-buttons:GoogleSocialButtons": d59.GoogleSocialButtons as ComponentType,
    "social-buttons:FacebookSocialButtons": d59.FacebookSocialButtons as ComponentType,
    "social-buttons:AppleSocialButtons": d59.AppleSocialButtons as ComponentType,
    "social-buttons:TwitterSocialButtons": d59.TwitterSocialButtons as ComponentType,
    "social-buttons:FigmaSocialButtons": d59.FigmaSocialButtons as ComponentType,
    "social-buttons:DribbleSocialButtons": d59.DribbleSocialButtons as ComponentType,
    "social-buttons:BrandSocialButtonsGroup": d59.BrandSocialButtonsGroup as ComponentType,
    "social-buttons:IconsBrandSocialButtonsGroup": d59.IconsBrandSocialButtonsGroup as ComponentType,
    "social-buttons:ColorSocialButtonsGroup": d59.ColorSocialButtonsGroup as ComponentType,
    "social-buttons:IconsColorSocialButtonsGroup": d59.IconsColorSocialButtonsGroup as ComponentType,
    "social-buttons:GraySocialButtonsGroup": d59.GraySocialButtonsGroup as ComponentType,
    "checkbox:CheckboxExample": d60.CheckboxExample as ComponentType,
    "checkbox:Base": d60.Base as ComponentType,
    "checkbox:WithLabel": d60.WithLabel as ComponentType,
    "checkbox:WithLabelAndHint": d60.WithLabelAndHint as ComponentType,
    "checkbox:Disabled": d60.Disabled as ComponentType,
    "checkbox:Sizes": d60.Sizes as ComponentType,
    "context-menus:ContextMenuExample": d61.ContextMenuExample as ComponentType,
    "context-menus:Simple": d61.Simple as ComponentType,
    "context-menus:Advanced": d61.Advanced as ComponentType,
    "dropdown:DropdownExample": d62.DropdownExample as ComponentType,
    "dropdown:ButtonSimple": d62.ButtonSimple as ComponentType,
    "dropdown:ButtonAdvanced": d62.ButtonAdvanced as ComponentType,
    "dropdown:ButtonLink": d62.ButtonLink as ComponentType,
    "dropdown:IconSimple": d62.IconSimple as ComponentType,
    "dropdown:IconAdvanced": d62.IconAdvanced as ComponentType,
    "dropdown:SearchSimple": d62.SearchSimple as ComponentType,
    "dropdown:SearchAdvanced": d62.SearchAdvanced as ComponentType,
    "dropdown:Integrations": d62.Integrations as ComponentType,
    "dropdown:AccountButton": d62.AccountButton as ComponentType,
    "dropdown:Avatar": d62.Avatar as ComponentType,
    "dropdown:AccountCardXs": d62.AccountCardXs as ComponentType,
    "dropdown:AccountCardSm": d62.AccountCardSm as ComponentType,
    "dropdown:AccountCardMd": d62.AccountCardMd as ComponentType,
    "dropdown:AccountBreadcrumb": d62.AccountBreadcrumb as ComponentType,
    "inputs:InputExample": d63.InputExample as ComponentType,
    "inputs:Default": d63.Default as ComponentType,
    "inputs:Disabled": d63.Disabled as ComponentType,
    "inputs:Invalid": d63.Invalid as ComponentType,
    "inputs:Sizes": d63.Sizes as ComponentType,
    "inputs:LeadingIcon": d63.LeadingIcon as ComponentType,
    "inputs:LeadingDropdown": d63.LeadingDropdown as ComponentType,
    "inputs:TrailingDropdown": d63.TrailingDropdown as ComponentType,
    "inputs:LeadingText": d63.LeadingText as ComponentType,
    "inputs:PaymentInput": d63.PaymentInput as ComponentType,
    "inputs:TrailingButton": d63.TrailingButton as ComponentType,
    "inputs:FileUpload": d63.FileUpload as ComponentType,
    "inputs:PasswordInput": d63.PasswordInput as ComponentType,
    "inputs:DateInput": d63.DateInput as ComponentType,
    "inputs:NumberInputHorizontal": d63.NumberInputHorizontal as ComponentType,
    "inputs:NumberInputVertical": d63.NumberInputVertical as ComponentType,
    "inputs:TagInput": d63.TagInput as ComponentType,
    "inputs:TagInputOuter": d63.TagInputOuter as ComponentType,
    "pin-input:VerificationCodeInputExample": d64.VerificationCodeInputExample as ComponentType,
    "pin-input:FourDigits": d64.FourDigits as ComponentType,
    "pin-input:WithSeparator": d64.WithSeparator as ComponentType,
    "pin-input:InputOTP": d64.InputOTP as ComponentType,
    "pin-input:Disabled": d64.Disabled as ComponentType,
    "pin-input:Sizes": d64.Sizes as ComponentType,
    "popover:PopoverExample": d65.PopoverExample as ComponentType,
    "popover:Placements": d65.Placements as ComponentType,
    "popover:WithIconTrigger": d65.WithIconTrigger as ComponentType,
    "progress-indicators:ProgressIndicatorExample": d66.ProgressIndicatorExample as ComponentType,
    "progress-indicators:Default": d66.Default as ComponentType,
    "progress-indicators:TextRight": d66.TextRight as ComponentType,
    "progress-indicators:TextBottom": d66.TextBottom as ComponentType,
    "progress-indicators:TextTopFloating": d66.TextTopFloating as ComponentType,
    "progress-indicators:TextBottomFloating": d66.TextBottomFloating as ComponentType,
    "progress-indicators:CircleProgressBar": d66.CircleProgressBar as ComponentType,
    "progress-indicators:CircleProgressBarLabel": d66.CircleProgressBarLabel as ComponentType,
    "progress-indicators:HalfCircleProgressBar": d66.HalfCircleProgressBar as ComponentType,
    "progress-indicators:HalfCircleProgressBarLabel": d66.HalfCircleProgressBarLabel as ComponentType,
    "radio-buttons:RadioButtonExample": d67.RadioButtonExample as ComponentType,
    "radio-buttons:WithLabel": d67.WithLabel as ComponentType,
    "radio-buttons:WithLabelAndHint": d67.WithLabelAndHint as ComponentType,
    "radio-buttons:Disabled": d67.Disabled as ComponentType,
    "radio-buttons:DisabledIndividualOption": d67.DisabledIndividualOption as ComponentType,
    "radio-buttons:Sizes": d67.Sizes as ComponentType,
    "radio-buttons:IconSimple": d67.IconSimple as ComponentType,
    "radio-buttons:IconCard": d67.IconCard as ComponentType,
    "radio-buttons:Avatar": d67.Avatar as ComponentType,
    "radio-buttons:PaymentIcon": d67.PaymentIcon as ComponentType,
    "radio-buttons:RadioButton": d67.RadioButton as ComponentType,
    "radio-buttons:Checkbox": d67.Checkbox as ComponentType,
    "multi-select:MultiSelectExample": d68.MultiSelectExample as ComponentType,
    "multi-select:Default": d68.Default as ComponentType,
    "multi-select:WithLeadingIcon": d68.WithLeadingIcon as ComponentType,
    "multi-select:Disabled": d68.Disabled as ComponentType,
    "multi-select:Sizes": d68.Sizes as ComponentType,
    "select:SelectExample": d69.SelectExample as ComponentType,
    "select:Default": d69.Default as ComponentType,
    "select:Disabled": d69.Disabled as ComponentType,
    "select:Sizes": d69.Sizes as ComponentType,
    "select:IconLeading": d69.IconLeading as ComponentType,
    "select:AvatarLeading": d69.AvatarLeading as ComponentType,
    "select:DotLeading": d69.DotLeading as ComponentType,
    "select:Search": d69.Search as ComponentType,
    "select:Tags": d69.Tags as ComponentType,
    "skeleton:SkeletonExample": d70.SkeletonExample as ComponentType,
    "skeleton:Avatar": d70.Avatar as ComponentType,
    "skeleton:TextBlock": d70.TextBlock as ComponentType,
    "skeleton:CardSkeleton": d70.CardSkeleton as ComponentType,
    "slider:SliderExample": d71.SliderExample as ComponentType,
    "slider:Default": d71.Default as ComponentType,
    "slider:BottomLabel": d71.BottomLabel as ComponentType,
    "slider:TopFloating": d71.TopFloating as ComponentType,
    "slider:SingleThumb": d71.SingleThumb as ComponentType,
    "tags:TagsExample": d72.TagsExample as ComponentType,
    "tags:SizesExample": d72.SizesExample as ComponentType,
    "tags:CloseXExample": d72.CloseXExample as ComponentType,
    "tags:CountExample": d72.CountExample as ComponentType,
    "tags:CheckboxExample": d72.CheckboxExample as ComponentType,
    "tags:CheckboxCloseXExample": d72.CheckboxCloseXExample as ComponentType,
    "tags:CheckboxCountExample": d72.CheckboxCountExample as ComponentType,
    "text-editor:TextEditorExample": d73.TextEditorExample as ComponentType,
    "text-editor:DefaultSm": d73.DefaultSm as ComponentType,
    "text-editor:DefaultMd": d73.DefaultMd as ComponentType,
    "text-editor:FloatingToolbarSm": d73.FloatingToolbarSm as ComponentType,
    "text-editor:FloatingToolbarMd": d73.FloatingToolbarMd as ComponentType,
    "text-editor:WithTooltip": d73.WithTooltip as ComponentType,
    "textarea:TextareaExample": d74.TextareaExample as ComponentType,
    "textarea:Default": d74.Default as ComponentType,
    "textarea:Disabled": d74.Disabled as ComponentType,
    "textarea:Invalid": d74.Invalid as ComponentType,
    "toggle-chip:ToggleChipExample": d75.ToggleChipExample as ComponentType,
    "toggle-chip:Colors": d75.Colors as ComponentType,
    "toggle-chip:Sizes": d75.Sizes as ComponentType,
    "toggle-chip:FilterGroup": d75.FilterGroup as ComponentType,
    "toggle-chip:Disabled": d75.Disabled as ComponentType,
    "toggle:ToggleExample": d76.ToggleExample as ComponentType,
    "toggle:Base": d76.Base as ComponentType,
    "toggle:WithLabel": d76.WithLabel as ComponentType,
    "toggle:WithLabelAndHint": d76.WithLabelAndHint as ComponentType,
    "toggle:Disabled": d76.Disabled as ComponentType,
    "toggle:Sizes": d76.Sizes as ComponentType,
    "toggle:Slim": d76.Slim as ComponentType,
    "toggle:SlimWithLabelAndHint": d76.SlimWithLabelAndHint as ComponentType,
    "tooltip:TooltipExample": d77.TooltipExample as ComponentType,
    "tooltip:DefaultExample": d77.DefaultExample as ComponentType,
    "tooltip:WithArrowExample": d77.WithArrowExample as ComponentType,
    "tooltip:WithSupportingTextExample": d77.WithSupportingTextExample as ComponentType,
    "tooltip:PlacementsExample": d77.PlacementsExample as ComponentType,
    "video-player:VideoPlayerExample": d78.VideoPlayerExample as ComponentType,
    "video-player:VideoPlayerSm": d78.VideoPlayerSm as ComponentType,
    "video-player:VideoPlayerMd": d78.VideoPlayerMd as ComponentType,
    "video-player:VideoPlayerLg": d78.VideoPlayerLg as ComponentType,
    "featured-icon:FeaturedIconExample": d79.FeaturedIconExample as ComponentType,
    "featured-icon:Light": d79.Light as ComponentType,
    "featured-icon:Gradient": d79.Gradient as ComponentType,
    "featured-icon:Dark": d79.Dark as ComponentType,
    "featured-icon:Outline": d79.Outline as ComponentType,
    "featured-icon:Modern": d79.Modern as ComponentType,
    "featured-icon:ModernNeue": d79.ModernNeue as ComponentType,
    "rating:RatingBadgeExample": d80.RatingBadgeExample as ComponentType,
    "rating:RatingStarsExample": d80.RatingStarsExample as ComponentType,
    "typography:ArticleExample": d81.ArticleExample as ComponentType,
    "typography:Headings": d81.Headings as ComponentType,
    "typography:Images": d81.Images as ComponentType,
    "typography:QuoteDefault": d81.QuoteDefault as ComponentType,
    "typography:QuoteWithAvatar": d81.QuoteWithAvatar as ComponentType,
    "typography:QuoteCentered": d81.QuoteCentered as ComponentType,
    "typography:QuoteMinimal": d81.QuoteMinimal as ComponentType,
    "typography:InlineCode": d81.InlineCode as ComponentType,
    "typography:FeatureText": d81.FeatureText as ComponentType,
    "404-pages:Page404Example": d82.Page404Example as ComponentType,
    "about-pages:AboutPageExample": d83.AboutPageExample as ComponentType,
    "blog-pages:BlogExample": d84.BlogExample as ComponentType,
    "blog-post-pages:BlogPostExample": d85.BlogPostExample as ComponentType,
    "contact-pages:ContactPageExample": d86.ContactPageExample as ComponentType,
    "faq-pages:FAQPageExample": d87.FAQPageExample as ComponentType,
    "landing-pages:LandingPageExample": d88.LandingPageExample as ComponentType,
    "legal-pages:LegalPageExample": d89.LegalPageExample as ComponentType,
    "pricing-pages:PricingPageExample": d90.PricingPageExample as ComponentType,
    "team-pages:TeamPageExample": d91.TeamPageExample as ComponentType,
    "banners:BannerExample": d92.BannerExample as ComponentType,
    "blog-sections:BlogSectionExample": d93.BlogSectionExample as ComponentType,
    "careers-sections:CareersSectionExample": d94.CareersSectionExample as ComponentType,
    "contact-sections:ContactSectionExample": d95.ContactSectionExample as ComponentType,
    "content-rich-text-sections:ContentRichTextSectionExample": d96.ContentRichTextSectionExample as ComponentType,
    "cta-sections:CTASectionExample": d97.CTASectionExample as ComponentType,
    "faq-sections:FAQSectionExample": d98.FAQSectionExample as ComponentType,
    "features-sections:FeaturesSectionExample": d99.FeaturesSectionExample as ComponentType,
    "footers:FooterExample": d100.FooterExample as ComponentType,
    "header-navigations:HeaderNavigationExample": d101.HeaderNavigationExample as ComponentType,
    "header-sections:HeaderSectionExample": d102.HeaderSectionExample as ComponentType,
    "hero-header-sections:HeroHeaderSectionExample": d103.HeroHeaderSectionExample as ComponentType,
    "metrics-sections:MetricsSectionExample": d104.MetricsSectionExample as ComponentType,
    "newsletter-cta-sections:NewsletterCTASectionExample": d105.NewsletterCTASectionExample as ComponentType,
    "pricing-sections:PricingSectionExample": d106.PricingSectionExample as ComponentType,
    "social-proof-sections:SocialProofSectionExample": d107.SocialProofSectionExample as ComponentType,
    "team-sections:TeamSectionExample": d108.TeamSectionExample as ComponentType,
    "testimonial-sections:TestimonialsSectionExample": d109.TestimonialsSectionExample as ComponentType,
    "credit-card:CreditCardExample": d110.CreditCardExample as ComponentType,
    "credit-card:CustomizationExample": d110.CustomizationExample as ComponentType,
    "credit-card:SizesExample": d110.SizesExample as ComponentType,
    "credit-card:Transparent": d110.Transparent as ComponentType,
    "credit-card:TransparentGradient": d110.TransparentGradient as ComponentType,
    "credit-card:BrandDark": d110.BrandDark as ComponentType,
    "credit-card:BrandLight": d110.BrandLight as ComponentType,
    "credit-card:GrayDark": d110.GrayDark as ComponentType,
    "credit-card:GrayLight": d110.GrayLight as ComponentType,
    "credit-card:TransparentStrip": d110.TransparentStrip as ComponentType,
    "credit-card:GrayStrip": d110.GrayStrip as ComponentType,
    "credit-card:GradientStrip": d110.GradientStrip as ComponentType,
    "credit-card:SalmonStrip": d110.SalmonStrip as ComponentType,
    "credit-card:GrayStripVertical": d110.GrayStripVertical as ComponentType,
    "credit-card:GradientStripVertical": d110.GradientStripVertical as ComponentType,
    "credit-card:SalmonStripVertical": d110.SalmonStripVertical as ComponentType,
    "illustrations:IllustrationExample": d111.IllustrationExample as ComponentType,
    "illustrations:BoxSm": d111.BoxSm as ComponentType,
    "illustrations:BoxMd": d111.BoxMd as ComponentType,
    "illustrations:BoxLg": d111.BoxLg as ComponentType,
    "illustrations:CloudSm": d111.CloudSm as ComponentType,
    "illustrations:CloudMd": d111.CloudMd as ComponentType,
    "illustrations:CloudLg": d111.CloudLg as ComponentType,
    "illustrations:CreditCardSm": d111.CreditCardSm as ComponentType,
    "illustrations:CreditCardMd": d111.CreditCardMd as ComponentType,
    "illustrations:CreditCardLg": d111.CreditCardLg as ComponentType,
    "illustrations:DocumentsSm": d111.DocumentsSm as ComponentType,
    "illustrations:DocumentsMd": d111.DocumentsMd as ComponentType,
    "illustrations:DocumentsLg": d111.DocumentsLg as ComponentType,
    "qr-code:QRCodeExample": d112.QRCodeExample as ComponentType,
    "qr-code:DefaultExample": d112.DefaultExample as ComponentType,
    "qr-code:LargeExample": d112.LargeExample as ComponentType,
    "qr-code:WithGradientScanExample": d112.WithGradientScanExample as ComponentType,
    "qr-code:WithCustomOptionsExample": d112.WithCustomOptionsExample as ComponentType,
};
