// GENERATED FILE — do not edit by hand. Run `pnpm gen:demos`.
import type { ComponentType } from "react";
import * as d0 from "@properui/ui/components/app-examples/404-sections/404-sections.demo";
import * as d1 from "@properui/ui/components/app-examples/dashboards-02/dashboards-02.demo";
import * as d2 from "@properui/ui/components/app-examples/dashboards/dashboards.demo";
import * as d3 from "@properui/ui/components/app-examples/email-templates/email-templates.demo";
import * as d4 from "@properui/ui/components/app-examples/forgot-password-pages/forgot-password-pages.demo";
import * as d5 from "@properui/ui/components/app-examples/informational-pages-02/informational-pages-02.demo";
import * as d6 from "@properui/ui/components/app-examples/informational-pages/informational-pages.demo";
import * as d7 from "@properui/ui/components/app-examples/log-in-pages/log-in-pages.demo";
import * as d8 from "@properui/ui/components/app-examples/settings-pages-02/settings-pages-02.demo";
import * as d9 from "@properui/ui/components/app-examples/settings-pages/settings-pages.demo";
import * as d10 from "@properui/ui/components/app-examples/sign-up-pages/sign-up-pages.demo";
import * as d11 from "@properui/ui/components/app-examples/verification-pages/verification-pages.demo";
import * as d12 from "@properui/ui/components/application/activity-feed/activity-feed.demo";
import * as d13 from "@properui/ui/components/application/alerts/alerts.demo";
import * as d14 from "@properui/ui/components/application/app-navigation/header-navigation.demo";
import * as d15 from "@properui/ui/components/application/app-navigation/sidebar-navigation.demo";
import * as d16 from "@properui/ui/components/application/breadcrumbs/breadcrumbs.demo";
import * as d17 from "@properui/ui/components/application/card-headers/card-headers.demo";
import * as d18 from "@properui/ui/components/application/carousel/carousel.demo";
import * as d19 from "@properui/ui/components/application/charts/activity-gauges.demo";
import * as d20 from "@properui/ui/components/application/charts/line-bar-charts.demo";
import * as d21 from "@properui/ui/components/application/charts/pie-charts.demo";
import * as d22 from "@properui/ui/components/application/charts/radar-charts.demo";
import * as d23 from "@properui/ui/components/application/code-snippet/code-snippet.demo";
import * as d24 from "@properui/ui/components/application/color-picker/color-picker.demo";
import * as d25 from "@properui/ui/components/application/command-menu/command-menu.demo";
import * as d26 from "@properui/ui/components/application/content-divider/content-divider.demo";
import * as d27 from "@properui/ui/components/application/date-picker/calendar.demo";
import * as d28 from "@properui/ui/components/application/date-picker/date-pickers.demo";
import * as d29 from "@properui/ui/components/application/empty-state/empty-state.demo";
import * as d30 from "@properui/ui/components/application/file-upload/file-upload.demo";
import * as d31 from "@properui/ui/components/application/filter-bar/filter-bars.demo";
import * as d32 from "@properui/ui/components/application/gradient-picker/gradient-picker.demo";
import * as d33 from "@properui/ui/components/application/image-picker/image-picker.demo";
import * as d34 from "@properui/ui/components/application/inline-cta/inline-cta.demo";
import * as d35 from "@properui/ui/components/application/loading-indicator/loading-indicator.demo";
import * as d36 from "@properui/ui/components/application/messaging/messaging.demo";
import * as d37 from "@properui/ui/components/application/metrics/metrics.demo";
import * as d38 from "@properui/ui/components/application/modals/modals.demo";
import * as d39 from "@properui/ui/components/application/notifications/notifications.demo";
import * as d40 from "@properui/ui/components/application/page-headers/page-headers.demo";
import * as d41 from "@properui/ui/components/application/pagination/pagination.demo";
import * as d42 from "@properui/ui/components/application/progress-steps/progress-steps.demo";
import * as d43 from "@properui/ui/components/application/section-footers/section-footers.demo";
import * as d44 from "@properui/ui/components/application/section-headers/section-headers.demo";
import * as d45 from "@properui/ui/components/application/slideout-menus/slideout-menus.demo";
import * as d46 from "@properui/ui/components/application/table/table.demo";
import * as d47 from "@properui/ui/components/application/tabs/tabs.demo";
import * as d48 from "@properui/ui/components/application/tree-view/tree-view.demo";
import * as d49 from "@properui/ui/components/base/avatar/avatar.demo";
import * as d50 from "@properui/ui/components/base/badges/badge-groups.demo";
import * as d51 from "@properui/ui/components/base/badges/badges.demo";
import * as d52 from "@properui/ui/components/base/button-group/button-group.demo";
import * as d53 from "@properui/ui/components/base/buttons/app-store-buttons.demo";
import * as d54 from "@properui/ui/components/base/buttons/button-utility.demo";
import * as d55 from "@properui/ui/components/base/buttons/buttons.demo";
import * as d56 from "@properui/ui/components/base/buttons/social-buttons.demo";
import * as d57 from "@properui/ui/components/base/checkbox/checkbox.demo";
import * as d58 from "@properui/ui/components/base/dropdown/context-menus.demo";
import * as d59 from "@properui/ui/components/base/dropdown/dropdown.demo";
import * as d60 from "@properui/ui/components/base/input/inputs.demo";
import * as d61 from "@properui/ui/components/base/input/pin-input.demo";
import * as d62 from "@properui/ui/components/base/progress-indicators/progress-indicators.demo";
import * as d63 from "@properui/ui/components/base/radio-buttons/radio-buttons.demo";
import * as d64 from "@properui/ui/components/base/select/multi-select.demo";
import * as d65 from "@properui/ui/components/base/select/select.demo";
import * as d66 from "@properui/ui/components/base/slider/slider.demo";
import * as d67 from "@properui/ui/components/base/tags/tags.demo";
import * as d68 from "@properui/ui/components/base/text-editor/text-editor.demo";
import * as d69 from "@properui/ui/components/base/textarea/textarea.demo";
import * as d70 from "@properui/ui/components/base/toggle/toggle.demo";
import * as d71 from "@properui/ui/components/base/tooltip/tooltip.demo";
import * as d72 from "@properui/ui/components/base/video-player/video-player.demo";
import * as d73 from "@properui/ui/components/foundations/featured-icon/featured-icon.demo";
import * as d74 from "@properui/ui/components/foundations/rating/rating.demo";
import * as d75 from "@properui/ui/components/foundations/typography/typography.demo";
import * as d76 from "@properui/ui/components/marketing-examples/404-pages/404-pages.demo";
import * as d77 from "@properui/ui/components/marketing-examples/about-pages/about-pages.demo";
import * as d78 from "@properui/ui/components/marketing-examples/blog-pages/blog-pages.demo";
import * as d79 from "@properui/ui/components/marketing-examples/blog-post-pages/blog-post-pages.demo";
import * as d80 from "@properui/ui/components/marketing-examples/contact-pages/contact-pages.demo";
import * as d81 from "@properui/ui/components/marketing-examples/faq-pages/faq-pages.demo";
import * as d82 from "@properui/ui/components/marketing-examples/landing-pages/landing-pages.demo";
import * as d83 from "@properui/ui/components/marketing-examples/legal-pages/legal-pages.demo";
import * as d84 from "@properui/ui/components/marketing-examples/pricing-pages/pricing-pages.demo";
import * as d85 from "@properui/ui/components/marketing-examples/team-pages/team-pages.demo";
import * as d86 from "@properui/ui/components/marketing/banners/banners.demo";
import * as d87 from "@properui/ui/components/marketing/blog-sections/blog-sections.demo";
import * as d88 from "@properui/ui/components/marketing/careers-sections/careers-sections.demo";
import * as d89 from "@properui/ui/components/marketing/contact-sections/contact-sections.demo";
import * as d90 from "@properui/ui/components/marketing/content-rich-text-sections/content-rich-text-sections.demo";
import * as d91 from "@properui/ui/components/marketing/cta-sections/cta-sections.demo";
import * as d92 from "@properui/ui/components/marketing/faq-sections/faq-sections.demo";
import * as d93 from "@properui/ui/components/marketing/features-sections/features-sections.demo";
import * as d94 from "@properui/ui/components/marketing/footers/footers.demo";
import * as d95 from "@properui/ui/components/marketing/header-navigations/header-navigations.demo";
import * as d96 from "@properui/ui/components/marketing/header-sections/header-sections.demo";
import * as d97 from "@properui/ui/components/marketing/hero-header-sections/hero-header-sections.demo";
import * as d98 from "@properui/ui/components/marketing/metrics-sections/metrics-sections.demo";
import * as d99 from "@properui/ui/components/marketing/newsletter-cta-sections/newsletter-cta-sections.demo";
import * as d100 from "@properui/ui/components/marketing/pricing-sections/pricing-sections.demo";
import * as d101 from "@properui/ui/components/marketing/social-proof-sections/social-proof-sections.demo";
import * as d102 from "@properui/ui/components/marketing/team-sections/team-sections.demo";
import * as d103 from "@properui/ui/components/marketing/testimonial-sections/testimonial-sections.demo";
import * as d104 from "@properui/ui/components/shared-assets/credit-card/credit-card.demo";
import * as d105 from "@properui/ui/components/shared-assets/illustrations/illustrations.demo";
import * as d106 from "@properui/ui/components/shared-assets/qr-code/qr-code.demo";

export const demos: Record<string, ComponentType> = {
    "404-sections:Section404Example": d0.Section404Example as ComponentType,
    "dashboards-02:DashboardWithHeaderNavigationExample": d1.DashboardWithHeaderNavigationExample as ComponentType,
    "dashboards:DashboardWithSidebarNavigationExample": d2.DashboardWithSidebarNavigationExample as ComponentType,
    "email-templates:EmailTemplateExample": d3.EmailTemplateExample as ComponentType,
    "forgot-password-pages:ForgotPasswordPageExample": d4.ForgotPasswordPageExample as ComponentType,
    "informational-pages-02:InformationalPageWithHeaderNavigationExample": d5.InformationalPageWithHeaderNavigationExample as ComponentType,
    "informational-pages:InformationalPageWithSidebarNavigationExample": d6.InformationalPageWithSidebarNavigationExample as ComponentType,
    "log-in-pages:LogInPageExample": d7.LogInPageExample as ComponentType,
    "settings-pages-02:SettingsPageWithHeaderNavigationExample": d8.SettingsPageWithHeaderNavigationExample as ComponentType,
    "settings-pages:SettingsPageWithSidebarNavigationExample": d9.SettingsPageWithSidebarNavigationExample as ComponentType,
    "sign-up-pages:SignUpPageExample": d10.SignUpPageExample as ComponentType,
    "verification-pages:VerificationPageExample": d11.VerificationPageExample as ComponentType,
    "activity-feed:ActivityFeedExample": d12.ActivityFeedExample as ComponentType,
    "activity-feed:ActivityFeedDivided": d12.ActivityFeedDivided as ComponentType,
    "activity-feed:ActivityFeedConnected": d12.ActivityFeedConnected as ComponentType,
    "activity-feed:ActivityFeedSpaced": d12.ActivityFeedSpaced as ComponentType,
    "activity-feed:MessagesDivided": d12.MessagesDivided as ComponentType,
    "activity-feed:MessagesConnected": d12.MessagesConnected as ComponentType,
    "activity-feed:MessagesSpaced": d12.MessagesSpaced as ComponentType,
    "alerts:AlertExample": d13.AlertExample as ComponentType,
    "alerts:FloatingDefault": d13.FloatingDefault as ComponentType,
    "alerts:FloatingBrand": d13.FloatingBrand as ComponentType,
    "alerts:FloatingGray": d13.FloatingGray as ComponentType,
    "alerts:FloatingError": d13.FloatingError as ComponentType,
    "alerts:FloatingWarning": d13.FloatingWarning as ComponentType,
    "alerts:FloatingSuccess": d13.FloatingSuccess as ComponentType,
    "alerts:FullWidthDefault": d13.FullWidthDefault as ComponentType,
    "alerts:FullWidthBrand": d13.FullWidthBrand as ComponentType,
    "alerts:FullWidthGray": d13.FullWidthGray as ComponentType,
    "alerts:FullWidthError": d13.FullWidthError as ComponentType,
    "alerts:FullWidthWarning": d13.FullWidthWarning as ComponentType,
    "alerts:FullWidthSuccess": d13.FullWidthSuccess as ComponentType,
    "header-navigation:HeaderNavigationExample": d14.HeaderNavigationExample as ComponentType,
    "header-navigation:Simple": d14.Simple as ComponentType,
    "header-navigation:DualTier": d14.DualTier as ComponentType,
    "sidebar-navigation:SidebarNavigationExample": d15.SidebarNavigationExample as ComponentType,
    "sidebar-navigation:Simple": d15.Simple as ComponentType,
    "sidebar-navigation:DualTier": d15.DualTier as ComponentType,
    "sidebar-navigation:Slim": d15.Slim as ComponentType,
    "sidebar-navigation:SectionsDividers": d15.SectionsDividers as ComponentType,
    "sidebar-navigation:SectionsSubheadings": d15.SectionsSubheadings as ComponentType,
    "sidebar-navigation:ProgressBar": d15.ProgressBar as ComponentType,
    "sidebar-navigation:ProgressCircle": d15.ProgressCircle as ComponentType,
    "sidebar-navigation:Image": d15.Image as ComponentType,
    "sidebar-navigation:CookiePreferences": d15.CookiePreferences as ComponentType,
    "sidebar-navigation:ReferralLink": d15.ReferralLink as ComponentType,
    "sidebar-navigation:OnboardingSteps": d15.OnboardingSteps as ComponentType,
    "sidebar-navigation:UpgradeCTA": d15.UpgradeCTA as ComponentType,
    "sidebar-navigation:SupportCTA": d15.SupportCTA as ComponentType,
    "sidebar-navigation:EventCTA": d15.EventCTA as ComponentType,
    "sidebar-navigation:Message": d15.Message as ComponentType,
    "sidebar-navigation:CurrentProjects": d15.CurrentProjects as ComponentType,
    "sidebar-navigation:FreeTrialCTA": d15.FreeTrialCTA as ComponentType,
    "sidebar-navigation:QRCode": d15.QRCode as ComponentType,
    "breadcrumbs:BreadcrumbsExample": d16.BreadcrumbsExample as ComponentType,
    "breadcrumbs:BreadcrumbsText": d16.BreadcrumbsText as ComponentType,
    "breadcrumbs:BreadcrumbsTextWithLine": d16.BreadcrumbsTextWithLine as ComponentType,
    "breadcrumbs:BreadcrumbsButton": d16.BreadcrumbsButton as ComponentType,
    "breadcrumbs:AccountButtonChevron": d16.AccountButtonChevron as ComponentType,
    "breadcrumbs:AccountButtonSlash": d16.AccountButtonSlash as ComponentType,
    "card-headers:CardHeaderExample": d17.CardHeaderExample as ComponentType,
    "card-headers:CardHeaderWithBadge": d17.CardHeaderWithBadge as ComponentType,
    "card-headers:CardHeaderWithAvatarAndBadge": d17.CardHeaderWithAvatarAndBadge as ComponentType,
    "carousel:CarouselExample": d18.CarouselExample as ComponentType,
    "carousel:CarouselMd": d18.CarouselMd as ComponentType,
    "carousel:CarouselLg": d18.CarouselLg as ComponentType,
    "activity-gauges:ActivityGaugeXs": d19.ActivityGaugeXs as ComponentType,
    "activity-gauges:ActivityGaugeSm": d19.ActivityGaugeSm as ComponentType,
    "activity-gauges:ActivityGaugeMd": d19.ActivityGaugeMd as ComponentType,
    "activity-gauges:ActivityGaugeLg": d19.ActivityGaugeLg as ComponentType,
    "activity-gauges:ActivityGaugeExample": d19.ActivityGaugeExample as ComponentType,
    "line-bar-charts:LineChart01": d20.LineChart01 as ComponentType,
    "line-bar-charts:LineChart02": d20.LineChart02 as ComponentType,
    "line-bar-charts:LineChart03": d20.LineChart03 as ComponentType,
    "line-bar-charts:LineChart04": d20.LineChart04 as ComponentType,
    "line-bar-charts:BarChart01": d20.BarChart01 as ComponentType,
    "line-bar-charts:BarChart02": d20.BarChart02 as ComponentType,
    "line-bar-charts:BarChart03": d20.BarChart03 as ComponentType,
    "line-bar-charts:LineChartExample": d20.LineChartExample as ComponentType,
    "pie-charts:PieChartXxl": d21.PieChartXxl as ComponentType,
    "pie-charts:PieChartXs": d21.PieChartXs as ComponentType,
    "pie-charts:PieChartSm": d21.PieChartSm as ComponentType,
    "pie-charts:PieChartMd": d21.PieChartMd as ComponentType,
    "pie-charts:PieChartLg": d21.PieChartLg as ComponentType,
    "pie-charts:PieChartExample": d21.PieChartExample as ComponentType,
    "radar-charts:RadarChart": d22.RadarChart as ComponentType,
    "radar-charts:RadarChartExample": d22.RadarChartExample as ComponentType,
    "code-snippet:CodeSnippetExample": d23.CodeSnippetExample as ComponentType,
    "code-snippet:WithLineNumber": d23.WithLineNumber as ComponentType,
    "code-snippet:WithoutLineNumber": d23.WithoutLineNumber as ComponentType,
    "code-snippet:ShowMore": d23.ShowMore as ComponentType,
    "code-snippet:WithTabs": d23.WithTabs as ComponentType,
    "color-picker:ColorPickerExample": d24.ColorPickerExample as ComponentType,
    "color-picker:ColorPicker": d24.ColorPicker as ComponentType,
    "color-picker:ColorSwatchPicker": d24.ColorSwatchPicker as ComponentType,
    "color-picker:SavedSwatchesSmall": d24.SavedSwatchesSmall as ComponentType,
    "color-picker:SavedSwatchesMedium": d24.SavedSwatchesMedium as ComponentType,
    "color-picker:BrandSwatches": d24.BrandSwatches as ComponentType,
    "color-picker:GraySwatches": d24.GraySwatches as ComponentType,
    "color-picker:MinimalPicker": d24.MinimalPicker as ComponentType,
    "color-picker:HueSlider": d24.HueSlider as ComponentType,
    "color-picker:TransparencySlider": d24.TransparencySlider as ComponentType,
    "color-picker:PalettePicker": d24.PalettePicker as ComponentType,
    "command-menu:CommandMenuExample": d25.CommandMenuExample as ComponentType,
    "command-menu:Users": d25.Users as ComponentType,
    "command-menu:UsersStacked": d25.UsersStacked as ComponentType,
    "command-menu:Actions": d25.Actions as ComponentType,
    "command-menu:ActionsStacked": d25.ActionsStacked as ComponentType,
    "command-menu:EmptyState": d25.EmptyState as ComponentType,
    "command-menu:UsersMenu": d25.UsersMenu as ComponentType,
    "command-menu:UsersMenuStacked": d25.UsersMenuStacked as ComponentType,
    "command-menu:IntegrationsMenu": d25.IntegrationsMenu as ComponentType,
    "command-menu:IntegrationsMenuStacked": d25.IntegrationsMenuStacked as ComponentType,
    "content-divider:ContentDividerExample": d26.ContentDividerExample as ComponentType,
    "content-divider:SingleLine": d26.SingleLine as ComponentType,
    "content-divider:DualLine": d26.DualLine as ComponentType,
    "content-divider:BackgroundFill": d26.BackgroundFill as ComponentType,
    "calendar:CalendarExample": d27.CalendarExample as ComponentType,
    "calendar:CalendarMonthView": d27.CalendarMonthView as ComponentType,
    "calendar:CalendarWeekView": d27.CalendarWeekView as ComponentType,
    "calendar:CalendarDayView": d27.CalendarDayView as ComponentType,
    "date-pickers:DatePickerExample": d28.DatePickerExample as ComponentType,
    "date-pickers:DatePicker": d28.DatePicker as ComponentType,
    "date-pickers:DateTimePicker": d28.DateTimePicker as ComponentType,
    "date-pickers:DateRangePickerWithPresets": d28.DateRangePickerWithPresets as ComponentType,
    "date-pickers:Calendar": d28.Calendar as ComponentType,
    "date-pickers:CalendarCard": d28.CalendarCard as ComponentType,
    "date-pickers:RangeCalendar": d28.RangeCalendar as ComponentType,
    "date-pickers:RangeCalendarCard": d28.RangeCalendarCard as ComponentType,
    "empty-state:EmptyStateExample": d29.EmptyStateExample as ComponentType,
    "empty-state:FeaturedIcon": d29.FeaturedIcon as ComponentType,
    "empty-state:Illustration": d29.Illustration as ComponentType,
    "empty-state:FileIcon": d29.FileIcon as ComponentType,
    "empty-state:AvatarRadius": d29.AvatarRadius as ComponentType,
    "empty-state:AvatarRow": d29.AvatarRow as ComponentType,
    "empty-state:AvatarGrid": d29.AvatarGrid as ComponentType,
    "file-upload:FileUploadExample": d30.FileUploadExample as ComponentType,
    "file-upload:ProgressBar": d30.ProgressBar as ComponentType,
    "file-upload:ProgressFill": d30.ProgressFill as ComponentType,
    "file-upload:Disabled": d30.Disabled as ComponentType,
    "file-upload:AcceptImageOnly": d30.AcceptImageOnly as ComponentType,
    "file-upload:MaxSizeLimit": d30.MaxSizeLimit as ComponentType,
    "filter-bars:FilterBarExample": d31.FilterBarExample as ComponentType,
    "filter-bars:Simple": d31.Simple as ComponentType,
    "filter-bars:TabsAndSearch": d31.TabsAndSearch as ComponentType,
    "filter-bars:TabsAndDatePicker": d31.TabsAndDatePicker as ComponentType,
    "filter-bars:DateFilters": d31.DateFilters as ComponentType,
    "filter-bars:Dropdowns": d31.Dropdowns as ComponentType,
    "filter-bars:DropdownsAndDatePicker": d31.DropdownsAndDatePicker as ComponentType,
    "filter-bars:AdvancedFilterInactive": d31.AdvancedFilterInactive as ComponentType,
    "filter-bars:AdvancedFilterActive": d31.AdvancedFilterActive as ComponentType,
    "filter-bars:FilterDropdownEmptyState": d31.FilterDropdownEmptyState as ComponentType,
    "filter-bars:FilterDropdownInactive": d31.FilterDropdownInactive as ComponentType,
    "filter-bars:FilterDropdownActive": d31.FilterDropdownActive as ComponentType,
    "filter-bars:FiltersAdvancedEmptyStateMenu": d31.FiltersAdvancedEmptyStateMenu as ComponentType,
    "filter-bars:FiltersAdvancedActiveMenu": d31.FiltersAdvancedActiveMenu as ComponentType,
    "gradient-picker:GradientPickerExample": d32.GradientPickerExample as ComponentType,
    "gradient-picker:GradientPicker": d32.GradientPicker as ComponentType,
    "image-picker:ImagePickerExample": d33.ImagePickerExample as ComponentType,
    "image-picker:ImagePicker": d33.ImagePicker as ComponentType,
    "inline-cta:InlineCTAExample": d34.InlineCTAExample as ComponentType,
    "inline-cta:Actions": d34.Actions as ComponentType,
    "inline-cta:EmailField": d34.EmailField as ComponentType,
    "inline-cta:ChangePlan": d34.ChangePlan as ComponentType,
    "inline-cta:UpgradePlan": d34.UpgradePlan as ComponentType,
    "inline-cta:PaymentMethod": d34.PaymentMethod as ComponentType,
    "inline-cta:Receipt": d34.Receipt as ComponentType,
    "loading-indicator:LoadingIndicatorExample": d35.LoadingIndicatorExample as ComponentType,
    "loading-indicator:LineSimple": d35.LineSimple as ComponentType,
    "loading-indicator:LineSimpleWithLabel": d35.LineSimpleWithLabel as ComponentType,
    "loading-indicator:LineSpinner": d35.LineSpinner as ComponentType,
    "loading-indicator:LineSpinnerWithLabel": d35.LineSpinnerWithLabel as ComponentType,
    "loading-indicator:DotCircle": d35.DotCircle as ComponentType,
    "loading-indicator:DotCircleWithLabel": d35.DotCircleWithLabel as ComponentType,
    "loading-indicator:Sizes": d35.Sizes as ComponentType,
    "messaging:MessagingExample": d36.MessagingExample as ComponentType,
    "messaging:MessageStatus": d36.MessageStatus as ComponentType,
    "messaging:MessageActionMinimal": d36.MessageActionMinimal as ComponentType,
    "messaging:MessageActionTextarea": d36.MessageActionTextarea as ComponentType,
    "messaging:MessageActionAdvanced": d36.MessageActionAdvanced as ComponentType,
    "messaging:MessageSimple": d36.MessageSimple as ComponentType,
    "messaging:MessageReactions": d36.MessageReactions as ComponentType,
    "messaging:MessageReply": d36.MessageReply as ComponentType,
    "messaging:MessageAttachment": d36.MessageAttachment as ComponentType,
    "messaging:MessageAudio": d36.MessageAudio as ComponentType,
    "messaging:MessageImage": d36.MessageImage as ComponentType,
    "messaging:MessageLinkPreview": d36.MessageLinkPreview as ComponentType,
    "messaging:MessageLinkMinimal": d36.MessageLinkMinimal as ComponentType,
    "messaging:MessageWriting": d36.MessageWriting as ComponentType,
    "metrics:MetricsExample": d37.MetricsExample as ComponentType,
    "metrics:Simple": d37.Simple as ComponentType,
    "metrics:SimpleActions": d37.SimpleActions as ComponentType,
    "metrics:MetricsIcon01": d37.MetricsIcon01 as ComponentType,
    "metrics:MetricsIconActions01": d37.MetricsIconActions01 as ComponentType,
    "metrics:MetricsIcon02": d37.MetricsIcon02 as ComponentType,
    "metrics:MetricsIconActions02": d37.MetricsIconActions02 as ComponentType,
    "metrics:MetricsIcon03": d37.MetricsIcon03 as ComponentType,
    "metrics:MetricsIconActions03": d37.MetricsIconActions03 as ComponentType,
    "metrics:MetricsIcon04": d37.MetricsIcon04 as ComponentType,
    "metrics:MetricsIconActions04": d37.MetricsIconActions04 as ComponentType,
    "metrics:Chart01": d37.Chart01 as ComponentType,
    "metrics:ChartActions01": d37.ChartActions01 as ComponentType,
    "metrics:Chart02": d37.Chart02 as ComponentType,
    "metrics:ChartActions02": d37.ChartActions02 as ComponentType,
    "metrics:Chart03": d37.Chart03 as ComponentType,
    "metrics:ChartActions03": d37.ChartActions03 as ComponentType,
    "metrics:Chart04": d37.Chart04 as ComponentType,
    "metrics:ChartActions04": d37.ChartActions04 as ComponentType,
    "modals:ModalExample": d38.ModalExample as ComponentType,
    "modals:StackedLeftAligned": d38.StackedLeftAligned as ComponentType,
    "modals:WarningStackedLeftAligned": d38.WarningStackedLeftAligned as ComponentType,
    "modals:DestructiveStackedLeftAligned": d38.DestructiveStackedLeftAligned as ComponentType,
    "modals:Horizontal": d38.Horizontal as ComponentType,
    "modals:WarningHorizontal": d38.WarningHorizontal as ComponentType,
    "modals:DestructiveHorizontal": d38.DestructiveHorizontal as ComponentType,
    "modals:Login": d38.Login as ComponentType,
    "modals:Signup01": d38.Signup01 as ComponentType,
    "modals:Signup02": d38.Signup02 as ComponentType,
    "modals:Checkboxes": d38.Checkboxes as ComponentType,
    "modals:Toggles": d38.Toggles as ComponentType,
    "modals:LinkField": d38.LinkField as ComponentType,
    "modals:Dropdown": d38.Dropdown as ComponentType,
    "modals:InputField": d38.InputField as ComponentType,
    "modals:Labels": d38.Labels as ComponentType,
    "modals:AccessRequest": d38.AccessRequest as ComponentType,
    "modals:EmailInvite": d38.EmailInvite as ComponentType,
    "modals:UserInvite": d38.UserInvite as ComponentType,
    "modals:StackedWithTeam": d38.StackedWithTeam as ComponentType,
    "modals:StackedWithTeamAndLink": d38.StackedWithTeamAndLink as ComponentType,
    "modals:StackedWithTeamAndInvites": d38.StackedWithTeamAndInvites as ComponentType,
    "modals:VerificationCode": d38.VerificationCode as ComponentType,
    "modals:TwoFactorCode": d38.TwoFactorCode as ComponentType,
    "modals:PasswordPrompt": d38.PasswordPrompt as ComponentType,
    "modals:CenteredPhoto": d38.CenteredPhoto as ComponentType,
    "modals:CenteredPhotoCarousel": d38.CenteredPhotoCarousel as ComponentType,
    "modals:CenteredVideoCarousel": d38.CenteredVideoCarousel as ComponentType,
    "modals:PaymentDetails": d38.PaymentDetails as ComponentType,
    "modals:PaymentDetailsWithImage": d38.PaymentDetailsWithImage as ComponentType,
    "modals:Plan01": d38.Plan01 as ComponentType,
    "modals:Plan02": d38.Plan02 as ComponentType,
    "modals:PaymentMethod": d38.PaymentMethod as ComponentType,
    "modals:DatePicker": d38.DatePicker as ComponentType,
    "modals:FileUpload": d38.FileUpload as ComponentType,
    "modals:ProfileSettings": d38.ProfileSettings as ComponentType,
    "modals:UserSelection": d38.UserSelection as ComponentType,
    "modals:Form01": d38.Form01 as ComponentType,
    "modals:Form02": d38.Form02 as ComponentType,
    "modals:ImageCrop": d38.ImageCrop as ComponentType,
    "modals:CalendarEvent": d38.CalendarEvent as ComponentType,
    "modals:BannerAppearance": d38.BannerAppearance as ComponentType,
    "modals:AppearanceSettings": d38.AppearanceSettings as ComponentType,
    "modals:AIAssistant": d38.AIAssistant as ComponentType,
    "modals:UserSettings": d38.UserSettings as ComponentType,
    "modals:NewProject": d38.NewProject as ComponentType,
    "modals:TextEditor": d38.TextEditor as ComponentType,
    "modals:ShareProject": d38.ShareProject as ComponentType,
    "modals:CreateEvent": d38.CreateEvent as ComponentType,
    "modals:Integration": d38.Integration as ComponentType,
    "modals:NewMessageEmptyState": d38.NewMessageEmptyState as ComponentType,
    "modals:NewMessageFilled": d38.NewMessageFilled as ComponentType,
    "notifications:NotificationExample": d39.NotificationExample as ComponentType,
    "notifications:IconDefault": d39.IconDefault as ComponentType,
    "notifications:IconGray": d39.IconGray as ComponentType,
    "notifications:IconBrand": d39.IconBrand as ComponentType,
    "notifications:IconError": d39.IconError as ComponentType,
    "notifications:IconWarning": d39.IconWarning as ComponentType,
    "notifications:IconSuccess": d39.IconSuccess as ComponentType,
    "notifications:ProgressNotification": d39.ProgressNotification as ComponentType,
    "notifications:ImageNotification": d39.ImageNotification as ComponentType,
    "notifications:AvatarNotification": d39.AvatarNotification as ComponentType,
    "page-headers:PageHeaderExample": d40.PageHeaderExample as ComponentType,
    "page-headers:Simple": d40.Simple as ComponentType,
    "page-headers:Avatar": d40.Avatar as ComponentType,
    "page-headers:BannerSimple": d40.BannerSimple as ComponentType,
    "page-headers:BannerAvatar": d40.BannerAvatar as ComponentType,
    "page-headers:BannerSimpleCentered": d40.BannerSimpleCentered as ComponentType,
    "page-headers:BannerAvatarCentered": d40.BannerAvatarCentered as ComponentType,
    "pagination:PaginationExample": d41.PaginationExample as ComponentType,
    "pagination:PageDefault": d41.PageDefault as ComponentType,
    "pagination:PageMinimalCenter": d41.PageMinimalCenter as ComponentType,
    "pagination:CardDefault": d41.CardDefault as ComponentType,
    "pagination:CardMinimalRightAligned": d41.CardMinimalRightAligned as ComponentType,
    "pagination:CardMinimalCenterAligned": d41.CardMinimalCenterAligned as ComponentType,
    "pagination:CardMinimalLeftAligned": d41.CardMinimalLeftAligned as ComponentType,
    "pagination:ButtonGroupRightAligned": d41.ButtonGroupRightAligned as ComponentType,
    "pagination:ButtonGroupCenterAligned": d41.ButtonGroupCenterAligned as ComponentType,
    "pagination:ButtonGroupLeftAligned": d41.ButtonGroupLeftAligned as ComponentType,
    "pagination:CardAdvanced": d41.CardAdvanced as ComponentType,
    "pagination:CardAdvancedCenter": d41.CardAdvancedCenter as ComponentType,
    "pagination:PaginationDot": d41.PaginationDot as ComponentType,
    "pagination:PaginationLine": d41.PaginationLine as ComponentType,
    "progress-steps:ProgressStepsExample": d42.ProgressStepsExample as ComponentType,
    "progress-steps:IconCentered": d42.IconCentered as ComponentType,
    "progress-steps:IconCenteredWithNumber": d42.IconCenteredWithNumber as ComponentType,
    "progress-steps:FeaturedIconCentered": d42.FeaturedIconCentered as ComponentType,
    "progress-steps:IconWithText": d42.IconWithText as ComponentType,
    "progress-steps:IconWithNumber": d42.IconWithNumber as ComponentType,
    "progress-steps:FeaturedIconWithText": d42.FeaturedIconWithText as ComponentType,
    "progress-steps:MinimalIcons": d42.MinimalIcons as ComponentType,
    "progress-steps:MinimalIconsConnected": d42.MinimalIconsConnected as ComponentType,
    "progress-steps:TextWithLine": d42.TextWithLine as ComponentType,
    "section-footers:SectionFooterExample": d43.SectionFooterExample as ComponentType,
    "section-footers:SectionFooterButtonGroup": d43.SectionFooterButtonGroup as ComponentType,
    "section-footers:SectionFooter": d43.SectionFooter as ComponentType,
    "section-footers:SectionFooterCardButtonGroup": d43.SectionFooterCardButtonGroup as ComponentType,
    "section-footers:SectionFooterCard": d43.SectionFooterCard as ComponentType,
    "section-headers:SectionHeaderExample": d44.SectionHeaderExample as ComponentType,
    "section-headers:SectionHeaderButtons": d44.SectionHeaderButtons as ComponentType,
    "section-headers:SectionHeaderSearchInput": d44.SectionHeaderSearchInput as ComponentType,
    "section-headers:SectionHeaderButtonGroup": d44.SectionHeaderButtonGroup as ComponentType,
    "section-headers:SectionHeaderButtonsWithTabs": d44.SectionHeaderButtonsWithTabs as ComponentType,
    "section-headers:SectionHeaderSearchInputWithTabs": d44.SectionHeaderSearchInputWithTabs as ComponentType,
    "section-headers:SectionHeaderButtonGroupsWithTabs": d44.SectionHeaderButtonGroupsWithTabs as ComponentType,
    "slideout-menus:DrawerExample": d45.DrawerExample as ComponentType,
    "slideout-menus:PlaceholderMenu": d45.PlaceholderMenu as ComponentType,
    "slideout-menus:UserProfileMenu": d45.UserProfileMenu as ComponentType,
    "slideout-menus:MessagesMenu": d45.MessagesMenu as ComponentType,
    "slideout-menus:MessageChatMenu": d45.MessageChatMenu as ComponentType,
    "slideout-menus:PaymentMethodMenu": d45.PaymentMethodMenu as ComponentType,
    "slideout-menus:PaymentDetailsMenu": d45.PaymentDetailsMenu as ComponentType,
    "slideout-menus:PlanMenu": d45.PlanMenu as ComponentType,
    "slideout-menus:TeamMembersMenu": d45.TeamMembersMenu as ComponentType,
    "slideout-menus:FiltersMenu": d45.FiltersMenu as ComponentType,
    "slideout-menus:FiltersAdvancedEmptyStateMenu": d45.FiltersAdvancedEmptyStateMenu as ComponentType,
    "slideout-menus:FiltersAdvancedActiveMenu": d45.FiltersAdvancedActiveMenu as ComponentType,
    "slideout-menus:FileUploadMenu": d45.FileUploadMenu as ComponentType,
    "slideout-menus:LabelsMenu": d45.LabelsMenu as ComponentType,
    "slideout-menus:ProjectDetailsMenu": d45.ProjectDetailsMenu as ComponentType,
    "slideout-menus:NotificationSettingsCheckboxMenu": d45.NotificationSettingsCheckboxMenu as ComponentType,
    "slideout-menus:NotificationSettingsButtonMenu": d45.NotificationSettingsButtonMenu as ComponentType,
    "slideout-menus:NotificationsMenu": d45.NotificationsMenu as ComponentType,
    "slideout-menus:OrderSummaryMenu": d45.OrderSummaryMenu as ComponentType,
    "slideout-menus:CalendarEventMenu": d45.CalendarEventMenu as ComponentType,
    "slideout-menus:UserSettingsMenu": d45.UserSettingsMenu as ComponentType,
    "slideout-menus:AIAssistantMenu": d45.AIAssistantMenu as ComponentType,
    "slideout-menus:AIAssistantMessageMenu": d45.AIAssistantMessageMenu as ComponentType,
    "slideout-menus:ShareProjectMenu": d45.ShareProjectMenu as ComponentType,
    "slideout-menus:CreateEventMenu": d45.CreateEventMenu as ComponentType,
    "slideout-menus:IntegrationMenu": d45.IntegrationMenu as ComponentType,
    "table:TableExample": d46.TableExample as ComponentType,
    "table:TableSmallSizeExample": d46.TableSmallSizeExample as ComponentType,
    "table:DividerLine01": d46.DividerLine01 as ComponentType,
    "table:AlternatingFills01": d46.AlternatingFills01 as ComponentType,
    "table:DividerLine02": d46.DividerLine02 as ComponentType,
    "table:AlternatingFills02": d46.AlternatingFills02 as ComponentType,
    "table:DividerLine03": d46.DividerLine03 as ComponentType,
    "table:AlternatingFills03": d46.AlternatingFills03 as ComponentType,
    "table:DividerLine04": d46.DividerLine04 as ComponentType,
    "table:AlternatingFills04": d46.AlternatingFills04 as ComponentType,
    "table:NoVendorsFound": d46.NoVendorsFound as ComponentType,
    "table:SomethingWentWrong": d46.SomethingWentWrong as ComponentType,
    "table:NoUsersFound": d46.NoUsersFound as ComponentType,
    "table:AddFirstIntegration": d46.AddFirstIntegration as ComponentType,
    "table:InviteFirstUser": d46.InviteFirstUser as ComponentType,
    "table:OfflineState": d46.OfflineState as ComponentType,
    "tabs:TabsExample": d47.TabsExample as ComponentType,
    "tabs:ButtonBrandHorizontal": d47.ButtonBrandHorizontal as ComponentType,
    "tabs:ButtonGrayHorizontal": d47.ButtonGrayHorizontal as ComponentType,
    "tabs:ButtonBorderHorizontal": d47.ButtonBorderHorizontal as ComponentType,
    "tabs:ButtonMinimalHorizontal": d47.ButtonMinimalHorizontal as ComponentType,
    "tabs:Underline": d47.Underline as ComponentType,
    "tabs:ButtonBrandVertical": d47.ButtonBrandVertical as ComponentType,
    "tabs:ButtonGrayVertical": d47.ButtonGrayVertical as ComponentType,
    "tabs:ButtonBorderVertical": d47.ButtonBorderVertical as ComponentType,
    "tabs:ButtonMinimalVertical": d47.ButtonMinimalVertical as ComponentType,
    "tabs:Line": d47.Line as ComponentType,
    "tree-view:TreeViewExample": d48.TreeViewExample as ComponentType,
    "tree-view:SimpleSm": d48.SimpleSm as ComponentType,
    "tree-view:SimpleMd": d48.SimpleMd as ComponentType,
    "tree-view:AdvancedSm": d48.AdvancedSm as ComponentType,
    "tree-view:AdvancedMd": d48.AdvancedMd as ComponentType,
    "avatar:AvatarExample": d49.AvatarExample as ComponentType,
    "avatar:Avatar": d49.Avatar as ComponentType,
    "avatar:BorderExample": d49.BorderExample as ComponentType,
    "avatar:StatusIndicatorExample": d49.StatusIndicatorExample as ComponentType,
    "avatar:CompanyLogoExample": d49.CompanyLogoExample as ComponentType,
    "avatar:VerifiedBadgeExample": d49.VerifiedBadgeExample as ComponentType,
    "avatar:PlaceholderExample": d49.PlaceholderExample as ComponentType,
    "avatar:InitialsExample": d49.InitialsExample as ComponentType,
    "avatar:LabelGroupExample": d49.LabelGroupExample as ComponentType,
    "avatar:GroupExample": d49.GroupExample as ComponentType,
    "avatar:ProfilePhoto": d49.ProfilePhoto as ComponentType,
    "avatar:ProfilePhotoPlaceholderExample": d49.ProfilePhotoPlaceholderExample as ComponentType,
    "avatar:ProfilePhotoInitialsExample": d49.ProfilePhotoInitialsExample as ComponentType,
    "badge-groups:BadgeGroupExample": d50.BadgeGroupExample as ComponentType,
    "badge-groups:PillColorLeadingGray": d50.PillColorLeadingGray as ComponentType,
    "badge-groups:PillColorLeadingBrand": d50.PillColorLeadingBrand as ComponentType,
    "badge-groups:PillColorLeadingError": d50.PillColorLeadingError as ComponentType,
    "badge-groups:PillColorLeadingWarning": d50.PillColorLeadingWarning as ComponentType,
    "badge-groups:PillColorLeadingSuccess": d50.PillColorLeadingSuccess as ComponentType,
    "badge-groups:PillColorTrailingGray": d50.PillColorTrailingGray as ComponentType,
    "badge-groups:PillColorTrailingBrand": d50.PillColorTrailingBrand as ComponentType,
    "badge-groups:PillColorTrailingError": d50.PillColorTrailingError as ComponentType,
    "badge-groups:PillColorTrailingWarning": d50.PillColorTrailingWarning as ComponentType,
    "badge-groups:PillColorTrailingSuccess": d50.PillColorTrailingSuccess as ComponentType,
    "badge-groups:ModernLeadingGray": d50.ModernLeadingGray as ComponentType,
    "badge-groups:ModernLeadingBrand": d50.ModernLeadingBrand as ComponentType,
    "badge-groups:ModernLeadingError": d50.ModernLeadingError as ComponentType,
    "badge-groups:ModernLeadingWarning": d50.ModernLeadingWarning as ComponentType,
    "badge-groups:ModernLeadingSuccess": d50.ModernLeadingSuccess as ComponentType,
    "badge-groups:ModernTrailingGray": d50.ModernTrailingGray as ComponentType,
    "badge-groups:ModernTrailingBrand": d50.ModernTrailingBrand as ComponentType,
    "badge-groups:ModernTrailingError": d50.ModernTrailingError as ComponentType,
    "badge-groups:ModernTrailingWarning": d50.ModernTrailingWarning as ComponentType,
    "badge-groups:ModernTrailingSuccess": d50.ModernTrailingSuccess as ComponentType,
    "badges:BadgeExample": d51.BadgeExample as ComponentType,
    "badges:PillColor": d51.PillColor as ComponentType,
    "badges:Color": d51.Color as ComponentType,
    "badges:Modern": d51.Modern as ComponentType,
    "badges:WithDot": d51.WithDot as ComponentType,
    "badges:WithDotBadgeColor": d51.WithDotBadgeColor as ComponentType,
    "badges:WithDotBadgeModern": d51.WithDotBadgeModern as ComponentType,
    "badges:WithFlag": d51.WithFlag as ComponentType,
    "badges:WithFlagBadgeColor": d51.WithFlagBadgeColor as ComponentType,
    "badges:WithFlagBadgeModern": d51.WithFlagBadgeModern as ComponentType,
    "badges:WithAvatar": d51.WithAvatar as ComponentType,
    "badges:WithAvatarBadgeColor": d51.WithAvatarBadgeColor as ComponentType,
    "badges:WithAvatarBadgeModern": d51.WithAvatarBadgeModern as ComponentType,
    "badges:WithCloseX": d51.WithCloseX as ComponentType,
    "badges:WithCloseXBadgeColor": d51.WithCloseXBadgeColor as ComponentType,
    "badges:WithCloseXBadgeModern": d51.WithCloseXBadgeModern as ComponentType,
    "badges:WithIconLeading": d51.WithIconLeading as ComponentType,
    "badges:ColorWithIconLeading": d51.ColorWithIconLeading as ComponentType,
    "badges:ModernWithIconLeading": d51.ModernWithIconLeading as ComponentType,
    "badges:WithIconTrailing": d51.WithIconTrailing as ComponentType,
    "badges:ColorWithIconTrailing": d51.ColorWithIconTrailing as ComponentType,
    "badges:ModernWithIconTrailing": d51.ModernWithIconTrailing as ComponentType,
    "badges:WithIconOnly": d51.WithIconOnly as ComponentType,
    "badges:ColorWithIconOnly": d51.ColorWithIconOnly as ComponentType,
    "badges:ModernWithIconOnly": d51.ModernWithIconOnly as ComponentType,
    "button-group:ButtonGroupExample": d52.ButtonGroupExample as ComponentType,
    "button-group:LeadingIcon": d52.LeadingIcon as ComponentType,
    "button-group:WithDot": d52.WithDot as ComponentType,
    "button-group:Disabled": d52.Disabled as ComponentType,
    "button-group:DisabledIndividualItem": d52.DisabledIndividualItem as ComponentType,
    "button-group:Selection": d52.Selection as ComponentType,
    "button-group:MultipleSelection": d52.MultipleSelection as ComponentType,
    "app-store-buttons:MobileAppStoreButtonsExample": d53.MobileAppStoreButtonsExample as ComponentType,
    "app-store-buttons:GooglePlayButtons": d53.GooglePlayButtons as ComponentType,
    "app-store-buttons:AppStoreButtons": d53.AppStoreButtons as ComponentType,
    "app-store-buttons:GalaxyStoreButtons": d53.GalaxyStoreButtons as ComponentType,
    "app-store-buttons:AppGalleryButtons": d53.AppGalleryButtons as ComponentType,
    "app-store-buttons:GooglePlayOutlineButtons": d53.GooglePlayOutlineButtons as ComponentType,
    "app-store-buttons:AppStoreOutlineButtons": d53.AppStoreOutlineButtons as ComponentType,
    "app-store-buttons:GalaxyStoreOutlineButtons": d53.GalaxyStoreOutlineButtons as ComponentType,
    "app-store-buttons:AppGalleryOutlineButtons": d53.AppGalleryOutlineButtons as ComponentType,
    "button-utility:UtilityButtonsExample": d54.UtilityButtonsExample as ComponentType,
    "button-utility:Secondary": d54.Secondary as ComponentType,
    "button-utility:Tertiary": d54.Tertiary as ComponentType,
    "button-utility:Sizes": d54.Sizes as ComponentType,
    "button-utility:Disabled": d54.Disabled as ComponentType,
    "button-utility:CloseX": d54.CloseX as ComponentType,
    "button-utility:CloseXDark": d54.CloseXDark as ComponentType,
    "buttons:ButtonExample": d55.ButtonExample as ComponentType,
    "buttons:PrimaryButtons": d55.PrimaryButtons as ComponentType,
    "buttons:SecondaryButtons": d55.SecondaryButtons as ComponentType,
    "buttons:TertiaryButtons": d55.TertiaryButtons as ComponentType,
    "buttons:LinkColorButtonsExample": d55.LinkColorButtonsExample as ComponentType,
    "buttons:LinkGrayButtons": d55.LinkGrayButtons as ComponentType,
    "buttons:IconLeadingButtonsExample": d55.IconLeadingButtonsExample as ComponentType,
    "buttons:IconTrailingButtonsExample": d55.IconTrailingButtonsExample as ComponentType,
    "buttons:IconOnlyButtonsExample": d55.IconOnlyButtonsExample as ComponentType,
    "buttons:LoadingButtonsExample": d55.LoadingButtonsExample as ComponentType,
    "buttons:DisabledButtonsExample": d55.DisabledButtonsExample as ComponentType,
    "buttons:PrimaryButtonsDestructiveExample": d55.PrimaryButtonsDestructiveExample as ComponentType,
    "buttons:SecondaryButtonsDestructive": d55.SecondaryButtonsDestructive as ComponentType,
    "buttons:TertiaryButtonsDestructive": d55.TertiaryButtonsDestructive as ComponentType,
    "social-buttons:SocialButtonsExample": d56.SocialButtonsExample as ComponentType,
    "social-buttons:GoogleSocialButtons": d56.GoogleSocialButtons as ComponentType,
    "social-buttons:FacebookSocialButtons": d56.FacebookSocialButtons as ComponentType,
    "social-buttons:AppleSocialButtons": d56.AppleSocialButtons as ComponentType,
    "social-buttons:TwitterSocialButtons": d56.TwitterSocialButtons as ComponentType,
    "social-buttons:FigmaSocialButtons": d56.FigmaSocialButtons as ComponentType,
    "social-buttons:DribbleSocialButtons": d56.DribbleSocialButtons as ComponentType,
    "social-buttons:BrandSocialButtonsGroup": d56.BrandSocialButtonsGroup as ComponentType,
    "social-buttons:IconsBrandSocialButtonsGroup": d56.IconsBrandSocialButtonsGroup as ComponentType,
    "social-buttons:ColorSocialButtonsGroup": d56.ColorSocialButtonsGroup as ComponentType,
    "social-buttons:IconsColorSocialButtonsGroup": d56.IconsColorSocialButtonsGroup as ComponentType,
    "social-buttons:GraySocialButtonsGroup": d56.GraySocialButtonsGroup as ComponentType,
    "checkbox:CheckboxExample": d57.CheckboxExample as ComponentType,
    "checkbox:Base": d57.Base as ComponentType,
    "checkbox:WithLabel": d57.WithLabel as ComponentType,
    "checkbox:WithLabelAndHint": d57.WithLabelAndHint as ComponentType,
    "checkbox:Disabled": d57.Disabled as ComponentType,
    "checkbox:Sizes": d57.Sizes as ComponentType,
    "context-menus:ContextMenuExample": d58.ContextMenuExample as ComponentType,
    "context-menus:Simple": d58.Simple as ComponentType,
    "context-menus:Advanced": d58.Advanced as ComponentType,
    "dropdown:DropdownExample": d59.DropdownExample as ComponentType,
    "dropdown:ButtonSimple": d59.ButtonSimple as ComponentType,
    "dropdown:ButtonAdvanced": d59.ButtonAdvanced as ComponentType,
    "dropdown:ButtonLink": d59.ButtonLink as ComponentType,
    "dropdown:IconSimple": d59.IconSimple as ComponentType,
    "dropdown:IconAdvanced": d59.IconAdvanced as ComponentType,
    "dropdown:SearchSimple": d59.SearchSimple as ComponentType,
    "dropdown:SearchAdvanced": d59.SearchAdvanced as ComponentType,
    "dropdown:Integrations": d59.Integrations as ComponentType,
    "dropdown:AccountButton": d59.AccountButton as ComponentType,
    "dropdown:Avatar": d59.Avatar as ComponentType,
    "dropdown:AccountCardXs": d59.AccountCardXs as ComponentType,
    "dropdown:AccountCardSm": d59.AccountCardSm as ComponentType,
    "dropdown:AccountCardMd": d59.AccountCardMd as ComponentType,
    "dropdown:AccountBreadcrumb": d59.AccountBreadcrumb as ComponentType,
    "inputs:InputExample": d60.InputExample as ComponentType,
    "inputs:Default": d60.Default as ComponentType,
    "inputs:Disabled": d60.Disabled as ComponentType,
    "inputs:Invalid": d60.Invalid as ComponentType,
    "inputs:Sizes": d60.Sizes as ComponentType,
    "inputs:LeadingIcon": d60.LeadingIcon as ComponentType,
    "inputs:LeadingDropdown": d60.LeadingDropdown as ComponentType,
    "inputs:TrailingDropdown": d60.TrailingDropdown as ComponentType,
    "inputs:LeadingText": d60.LeadingText as ComponentType,
    "inputs:PaymentInput": d60.PaymentInput as ComponentType,
    "inputs:TrailingButton": d60.TrailingButton as ComponentType,
    "inputs:FileUpload": d60.FileUpload as ComponentType,
    "inputs:PasswordInput": d60.PasswordInput as ComponentType,
    "inputs:DateInput": d60.DateInput as ComponentType,
    "inputs:NumberInputHorizontal": d60.NumberInputHorizontal as ComponentType,
    "inputs:NumberInputVertical": d60.NumberInputVertical as ComponentType,
    "inputs:TagInput": d60.TagInput as ComponentType,
    "inputs:TagInputOuter": d60.TagInputOuter as ComponentType,
    "pin-input:VerificationCodeInputExample": d61.VerificationCodeInputExample as ComponentType,
    "pin-input:FourDigits": d61.FourDigits as ComponentType,
    "pin-input:WithSeparator": d61.WithSeparator as ComponentType,
    "pin-input:InputOTP": d61.InputOTP as ComponentType,
    "pin-input:Disabled": d61.Disabled as ComponentType,
    "pin-input:Sizes": d61.Sizes as ComponentType,
    "progress-indicators:ProgressIndicatorExample": d62.ProgressIndicatorExample as ComponentType,
    "progress-indicators:Default": d62.Default as ComponentType,
    "progress-indicators:TextRight": d62.TextRight as ComponentType,
    "progress-indicators:TextBottom": d62.TextBottom as ComponentType,
    "progress-indicators:TextTopFloating": d62.TextTopFloating as ComponentType,
    "progress-indicators:TextBottomFloating": d62.TextBottomFloating as ComponentType,
    "progress-indicators:CircleProgressBar": d62.CircleProgressBar as ComponentType,
    "progress-indicators:CircleProgressBarLabel": d62.CircleProgressBarLabel as ComponentType,
    "progress-indicators:HalfCircleProgressBar": d62.HalfCircleProgressBar as ComponentType,
    "progress-indicators:HalfCircleProgressBarLabel": d62.HalfCircleProgressBarLabel as ComponentType,
    "radio-buttons:RadioButtonExample": d63.RadioButtonExample as ComponentType,
    "radio-buttons:WithLabel": d63.WithLabel as ComponentType,
    "radio-buttons:WithLabelAndHint": d63.WithLabelAndHint as ComponentType,
    "radio-buttons:Disabled": d63.Disabled as ComponentType,
    "radio-buttons:DisabledIndividualOption": d63.DisabledIndividualOption as ComponentType,
    "radio-buttons:Sizes": d63.Sizes as ComponentType,
    "radio-buttons:IconSimple": d63.IconSimple as ComponentType,
    "radio-buttons:IconCard": d63.IconCard as ComponentType,
    "radio-buttons:Avatar": d63.Avatar as ComponentType,
    "radio-buttons:PaymentIcon": d63.PaymentIcon as ComponentType,
    "radio-buttons:RadioButton": d63.RadioButton as ComponentType,
    "radio-buttons:Checkbox": d63.Checkbox as ComponentType,
    "multi-select:MultiSelectExample": d64.MultiSelectExample as ComponentType,
    "multi-select:Default": d64.Default as ComponentType,
    "multi-select:WithLeadingIcon": d64.WithLeadingIcon as ComponentType,
    "multi-select:Disabled": d64.Disabled as ComponentType,
    "multi-select:Sizes": d64.Sizes as ComponentType,
    "select:SelectExample": d65.SelectExample as ComponentType,
    "select:Default": d65.Default as ComponentType,
    "select:Disabled": d65.Disabled as ComponentType,
    "select:Sizes": d65.Sizes as ComponentType,
    "select:IconLeading": d65.IconLeading as ComponentType,
    "select:AvatarLeading": d65.AvatarLeading as ComponentType,
    "select:DotLeading": d65.DotLeading as ComponentType,
    "select:Search": d65.Search as ComponentType,
    "select:Tags": d65.Tags as ComponentType,
    "slider:SliderExample": d66.SliderExample as ComponentType,
    "slider:Default": d66.Default as ComponentType,
    "slider:BottomLabel": d66.BottomLabel as ComponentType,
    "slider:TopFloating": d66.TopFloating as ComponentType,
    "slider:SingleThumb": d66.SingleThumb as ComponentType,
    "tags:TagsExample": d67.TagsExample as ComponentType,
    "tags:SizesExample": d67.SizesExample as ComponentType,
    "tags:CloseXExample": d67.CloseXExample as ComponentType,
    "tags:CountExample": d67.CountExample as ComponentType,
    "tags:CheckboxExample": d67.CheckboxExample as ComponentType,
    "tags:CheckboxCloseXExample": d67.CheckboxCloseXExample as ComponentType,
    "tags:CheckboxCountExample": d67.CheckboxCountExample as ComponentType,
    "text-editor:TextEditorExample": d68.TextEditorExample as ComponentType,
    "text-editor:DefaultSm": d68.DefaultSm as ComponentType,
    "text-editor:DefaultMd": d68.DefaultMd as ComponentType,
    "text-editor:FloatingToolbarSm": d68.FloatingToolbarSm as ComponentType,
    "text-editor:FloatingToolbarMd": d68.FloatingToolbarMd as ComponentType,
    "text-editor:WithTooltip": d68.WithTooltip as ComponentType,
    "textarea:TextareaExample": d69.TextareaExample as ComponentType,
    "textarea:Default": d69.Default as ComponentType,
    "textarea:Disabled": d69.Disabled as ComponentType,
    "textarea:Invalid": d69.Invalid as ComponentType,
    "toggle:ToggleExample": d70.ToggleExample as ComponentType,
    "toggle:Base": d70.Base as ComponentType,
    "toggle:WithLabel": d70.WithLabel as ComponentType,
    "toggle:WithLabelAndHint": d70.WithLabelAndHint as ComponentType,
    "toggle:Disabled": d70.Disabled as ComponentType,
    "toggle:Sizes": d70.Sizes as ComponentType,
    "toggle:Slim": d70.Slim as ComponentType,
    "toggle:SlimWithLabelAndHint": d70.SlimWithLabelAndHint as ComponentType,
    "tooltip:TooltipExample": d71.TooltipExample as ComponentType,
    "tooltip:DefaultExample": d71.DefaultExample as ComponentType,
    "tooltip:WithArrowExample": d71.WithArrowExample as ComponentType,
    "tooltip:WithSupportingTextExample": d71.WithSupportingTextExample as ComponentType,
    "tooltip:PlacementsExample": d71.PlacementsExample as ComponentType,
    "video-player:VideoPlayerExample": d72.VideoPlayerExample as ComponentType,
    "video-player:VideoPlayerSm": d72.VideoPlayerSm as ComponentType,
    "video-player:VideoPlayerMd": d72.VideoPlayerMd as ComponentType,
    "video-player:VideoPlayerLg": d72.VideoPlayerLg as ComponentType,
    "featured-icon:FeaturedIconExample": d73.FeaturedIconExample as ComponentType,
    "featured-icon:Light": d73.Light as ComponentType,
    "featured-icon:Gradient": d73.Gradient as ComponentType,
    "featured-icon:Dark": d73.Dark as ComponentType,
    "featured-icon:Outline": d73.Outline as ComponentType,
    "featured-icon:Modern": d73.Modern as ComponentType,
    "featured-icon:ModernNeue": d73.ModernNeue as ComponentType,
    "rating:RatingBadgeExample": d74.RatingBadgeExample as ComponentType,
    "rating:RatingStarsExample": d74.RatingStarsExample as ComponentType,
    "typography:ArticleExample": d75.ArticleExample as ComponentType,
    "typography:Headings": d75.Headings as ComponentType,
    "typography:Images": d75.Images as ComponentType,
    "typography:QuoteDefault": d75.QuoteDefault as ComponentType,
    "typography:QuoteWithAvatar": d75.QuoteWithAvatar as ComponentType,
    "typography:QuoteCentered": d75.QuoteCentered as ComponentType,
    "typography:QuoteMinimal": d75.QuoteMinimal as ComponentType,
    "typography:InlineCode": d75.InlineCode as ComponentType,
    "typography:FeatureText": d75.FeatureText as ComponentType,
    "404-pages:Page404Example": d76.Page404Example as ComponentType,
    "about-pages:AboutPageExample": d77.AboutPageExample as ComponentType,
    "blog-pages:BlogExample": d78.BlogExample as ComponentType,
    "blog-post-pages:BlogPostExample": d79.BlogPostExample as ComponentType,
    "contact-pages:ContactPageExample": d80.ContactPageExample as ComponentType,
    "faq-pages:FAQPageExample": d81.FAQPageExample as ComponentType,
    "landing-pages:LandingPageExample": d82.LandingPageExample as ComponentType,
    "legal-pages:LegalPageExample": d83.LegalPageExample as ComponentType,
    "pricing-pages:PricingPageExample": d84.PricingPageExample as ComponentType,
    "team-pages:TeamPageExample": d85.TeamPageExample as ComponentType,
    "banners:BannerExample": d86.BannerExample as ComponentType,
    "blog-sections:BlogSectionExample": d87.BlogSectionExample as ComponentType,
    "careers-sections:CareersSectionExample": d88.CareersSectionExample as ComponentType,
    "contact-sections:ContactSectionExample": d89.ContactSectionExample as ComponentType,
    "content-rich-text-sections:ContentRichTextSectionExample": d90.ContentRichTextSectionExample as ComponentType,
    "cta-sections:CTASectionExample": d91.CTASectionExample as ComponentType,
    "faq-sections:FAQSectionExample": d92.FAQSectionExample as ComponentType,
    "features-sections:FeaturesSectionExample": d93.FeaturesSectionExample as ComponentType,
    "footers:FooterExample": d94.FooterExample as ComponentType,
    "header-navigations:HeaderNavigationExample": d95.HeaderNavigationExample as ComponentType,
    "header-sections:HeaderSectionExample": d96.HeaderSectionExample as ComponentType,
    "hero-header-sections:HeroHeaderSectionExample": d97.HeroHeaderSectionExample as ComponentType,
    "metrics-sections:MetricsSectionExample": d98.MetricsSectionExample as ComponentType,
    "newsletter-cta-sections:NewsletterCTASectionExample": d99.NewsletterCTASectionExample as ComponentType,
    "pricing-sections:PricingSectionExample": d100.PricingSectionExample as ComponentType,
    "social-proof-sections:SocialProofSectionExample": d101.SocialProofSectionExample as ComponentType,
    "team-sections:TeamSectionExample": d102.TeamSectionExample as ComponentType,
    "testimonial-sections:TestimonialsSectionExample": d103.TestimonialsSectionExample as ComponentType,
    "credit-card:CreditCardExample": d104.CreditCardExample as ComponentType,
    "credit-card:CustomizationExample": d104.CustomizationExample as ComponentType,
    "credit-card:SizesExample": d104.SizesExample as ComponentType,
    "credit-card:Transparent": d104.Transparent as ComponentType,
    "credit-card:TransparentGradient": d104.TransparentGradient as ComponentType,
    "credit-card:BrandDark": d104.BrandDark as ComponentType,
    "credit-card:BrandLight": d104.BrandLight as ComponentType,
    "credit-card:GrayDark": d104.GrayDark as ComponentType,
    "credit-card:GrayLight": d104.GrayLight as ComponentType,
    "credit-card:TransparentStrip": d104.TransparentStrip as ComponentType,
    "credit-card:GrayStrip": d104.GrayStrip as ComponentType,
    "credit-card:GradientStrip": d104.GradientStrip as ComponentType,
    "credit-card:SalmonStrip": d104.SalmonStrip as ComponentType,
    "credit-card:GrayStripVertical": d104.GrayStripVertical as ComponentType,
    "credit-card:GradientStripVertical": d104.GradientStripVertical as ComponentType,
    "credit-card:SalmonStripVertical": d104.SalmonStripVertical as ComponentType,
    "illustrations:IllustrationExample": d105.IllustrationExample as ComponentType,
    "illustrations:BoxSm": d105.BoxSm as ComponentType,
    "illustrations:BoxMd": d105.BoxMd as ComponentType,
    "illustrations:BoxLg": d105.BoxLg as ComponentType,
    "illustrations:CloudSm": d105.CloudSm as ComponentType,
    "illustrations:CloudMd": d105.CloudMd as ComponentType,
    "illustrations:CloudLg": d105.CloudLg as ComponentType,
    "illustrations:CreditCardSm": d105.CreditCardSm as ComponentType,
    "illustrations:CreditCardMd": d105.CreditCardMd as ComponentType,
    "illustrations:CreditCardLg": d105.CreditCardLg as ComponentType,
    "illustrations:DocumentsSm": d105.DocumentsSm as ComponentType,
    "illustrations:DocumentsMd": d105.DocumentsMd as ComponentType,
    "illustrations:DocumentsLg": d105.DocumentsLg as ComponentType,
    "qr-code:QRCodeExample": d106.QRCodeExample as ComponentType,
    "qr-code:DefaultExample": d106.DefaultExample as ComponentType,
    "qr-code:LargeExample": d106.LargeExample as ComponentType,
    "qr-code:WithGradientScanExample": d106.WithGradientScanExample as ComponentType,
    "qr-code:WithCustomOptionsExample": d106.WithCustomOptionsExample as ComponentType,
};
