// GENERATED FILE — do not edit by hand. Run `pnpm gen:variant-parts`.
import { variantsA } from "./variants.a";
import { variantsB } from "./variants.b";

export const variants = {
    "contact-simple-form": variantsA["contact-simple-form"],
    "contact-form-and-image-02": variantsA["contact-form-and-image-02"],
    "contact-map-01": variantsA["contact-map-01"],
    "contact-simple-icons-02": variantsA["contact-simple-icons-02"],
    "contact-icons-and-form": variantsA["contact-icons-and-form"],
    "contact-icons-and-image": variantsA["contact-icons-and-image"],
    "contact-icon-cards-03": variantsA["contact-icon-cards-03"],
    "contact-features-tabs-map-02": variantsA["contact-features-tabs-map-02"],
    "contact-simple-form-02": variantsA["contact-simple-form-02"],
    "contact-simple-form-05": variantsA["contact-simple-form-05"],
    "contact-simple-icons-03-brand": variantsA["contact-simple-icons-03-brand"],
    "contact-icons-and-map-01-brand": variantsA["contact-icons-and-map-01-brand"],
    "contact-form-and-map": variantsA["contact-form-and-map"],
    "contact-simple-links-01": variantsA["contact-simple-links-01"],
    "contact-map-02": variantsA["contact-map-02"],
    "contact-simple-icons-03": variantsA["contact-simple-icons-03"],
    "contact-icons-and-map-01": variantsA["contact-icons-and-map-01"],
    "contact-icon-cards-01": variantsA["contact-icon-cards-01"],
    "contact-centered-map": variantsB["contact-centered-map"],
    "contact-vector-map-03": variantsB["contact-vector-map-03"],
    "contact-simple-form-03": variantsB["contact-simple-form-03"],
    "contact-simple-icons-01-brand": variantsB["contact-simple-icons-01-brand"],
    "contact-simple-icons-04-brand": variantsB["contact-simple-icons-04-brand"],
    "contact-icons-and-map-02-brand": variantsB["contact-icons-and-map-02-brand"],
    "contact-form-and-image-01": variantsB["contact-form-and-image-01"],
    "contact-simple-links-02": variantsB["contact-simple-links-02"],
    "contact-simple-icons-01": variantsB["contact-simple-icons-01"],
    "contact-simple-icons-04": variantsB["contact-simple-icons-04"],
    "contact-icons-and-map-02": variantsB["contact-icons-and-map-02"],
    "contact-icon-cards-02": variantsB["contact-icon-cards-02"],
    "contact-features-tabs-map-01": variantsB["contact-features-tabs-map-01"],
    "contact-simple-form-01": variantsB["contact-simple-form-01"],
    "contact-simple-form-04": variantsB["contact-simple-form-04"],
    "contact-simple-icons-02-brand": variantsB["contact-simple-icons-02-brand"],
    "contact-icons-and-form-brand": variantsB["contact-icons-and-form-brand"],
    "contact-icons-and-image-brand": variantsB["contact-icons-and-image-brand"],
} as const;
