// GENERATED FILE — do not edit by hand. Run `pnpm gen:variant-parts`.
import { variantsA } from "./variants.a";
import { variantsB } from "./variants.b";

export const variants = {
    "hero-split-image-01": variantsA["hero-split-image-01"],
    "hero-split-image-04": variantsA["hero-split-image-04"],
    "hero-split-form-01": variantsA["hero-split-form-01"],
    "hero-abstract-angles-02": variantsA["hero-abstract-angles-02"],
    "hero-screen-mockup-01": variantsA["hero-screen-mockup-01"],
    "hero-screen-mockup-04": variantsA["hero-screen-mockup-04"],
    "hero-screen-mockup-07": variantsA["hero-screen-mockup-07"],
    "hero-iphone-mockup-02": variantsA["hero-iphone-mockup-02"],
    "hero-color-card-01": variantsA["hero-color-card-01"],
    "hero-color-card-04": variantsA["hero-color-card-04"],
    "hero-card-mockup-03": variantsA["hero-card-mockup-03"],
    "hero-card-mockup-06": variantsA["hero-card-mockup-06"],
    "hero-card-mockup-09": variantsA["hero-card-mockup-09"],
    "hero-simple-text-01": variantsA["hero-simple-text-01"],
    "hero-geometric-shapes-03": variantsA["hero-geometric-shapes-03"],
    "hero-split-image-02": variantsA["hero-split-image-02"],
    "hero-split-image-05": variantsA["hero-split-image-05"],
    "hero-split-form-02": variantsA["hero-split-form-02"],
    "hero-abstract-angles-03": variantsA["hero-abstract-angles-03"],
    "hero-screen-mockup-02": variantsA["hero-screen-mockup-02"],
    "hero-screen-mockup-05": variantsA["hero-screen-mockup-05"],
    "hero-screen-mockup-08": variantsA["hero-screen-mockup-08"],
    "hero-iphone-mockup-03": variantsB["hero-iphone-mockup-03"],
    "hero-color-card-02": variantsB["hero-color-card-02"],
    "hero-card-mockup-01": variantsB["hero-card-mockup-01"],
    "hero-card-mockup-04": variantsB["hero-card-mockup-04"],
    "hero-card-mockup-07": variantsB["hero-card-mockup-07"],
    "hero-card-mockup-10": variantsB["hero-card-mockup-10"],
    "hero-simple-text-02": variantsB["hero-simple-text-02"],
    "hero-geometric-shapes-04": variantsB["hero-geometric-shapes-04"],
    "hero-split-image-03": variantsB["hero-split-image-03"],
    "hero-split-image-06": variantsB["hero-split-image-06"],
    "hero-abstract-angles-01": variantsB["hero-abstract-angles-01"],
    "hero-abstract-angles-04": variantsB["hero-abstract-angles-04"],
    "hero-screen-mockup-03": variantsB["hero-screen-mockup-03"],
    "hero-screen-mockup-06": variantsB["hero-screen-mockup-06"],
    "hero-iphone-mockup-01": variantsB["hero-iphone-mockup-01"],
    "hero-iphone-mockup-04": variantsB["hero-iphone-mockup-04"],
    "hero-color-card-03": variantsB["hero-color-card-03"],
    "hero-card-mockup-02": variantsB["hero-card-mockup-02"],
    "hero-card-mockup-05": variantsB["hero-card-mockup-05"],
    "hero-card-mockup-08": variantsB["hero-card-mockup-08"],
    "hero-card-mockup-11": variantsB["hero-card-mockup-11"],
    "hero-geometric-shapes-01": variantsB["hero-geometric-shapes-01"],
} as const;
