// GENERATED FILE — do not edit by hand. Run `pnpm gen:variant-parts`.
import { variantsA } from "./variants.a";
import { variantsB } from "./variants.b";

export const variants = {
    "features-alternating-layout-01": variantsA["features-alternating-layout-01"],
    "features-alternating-layout-04": variantsA["features-alternating-layout-04"],
    "features-simple-icons-03": variantsA["features-simple-icons-03"],
    "features-icons-and-image-02": variantsA["features-icons-and-image-02"],
    "features-icon-cards-01": variantsA["features-icon-cards-01"],
    "features-center-mockup-02": variantsA["features-center-mockup-02"],
    "features-icons-and-mockup-03": variantsA["features-icons-and-mockup-03"],
    "features-icons-and-mockup-06": variantsA["features-icons-and-mockup-06"],
    "features-large-screen-mockup-01": variantsA["features-large-screen-mockup-01"],
    "features-tabs-mockup-02": variantsA["features-tabs-mockup-02"],
    "features-tabs-mockup-05": variantsA["features-tabs-mockup-05"],
    "features-tabs-mockup-08": variantsA["features-tabs-mockup-08"],
    "features-tabs-mockup-11": variantsA["features-tabs-mockup-11"],
    "features-integrations-icons-02": variantsA["features-integrations-icons-02"],
    "features-simple-icons-01-brand": variantsA["features-simple-icons-01-brand"],
    "features-simple-icons-04-brand": variantsA["features-simple-icons-04-brand"],
    "features-alternating-layout-02": variantsA["features-alternating-layout-02"],
    "features-simple-icons-01": variantsA["features-simple-icons-01"],
    "features-simple-icons-04": variantsA["features-simple-icons-04"],
    "features-icons-and-image-03": variantsA["features-icons-and-image-03"],
    "features-icon-cards-02": variantsA["features-icon-cards-02"],
    "features-icons-and-mockup-01": variantsA["features-icons-and-mockup-01"],
    "features-icons-and-mockup-04": variantsA["features-icons-and-mockup-04"],
    "features-icons-and-mockup-07": variantsB["features-icons-and-mockup-07"],
    "features-large-screen-mockup-02": variantsB["features-large-screen-mockup-02"],
    "features-tabs-mockup-03": variantsB["features-tabs-mockup-03"],
    "features-tabs-mockup-06": variantsB["features-tabs-mockup-06"],
    "features-tabs-mockup-09": variantsB["features-tabs-mockup-09"],
    "features-tabs-mockup-12": variantsB["features-tabs-mockup-12"],
    "features-integrations-icons-03": variantsB["features-integrations-icons-03"],
    "features-simple-icons-02-brand": variantsB["features-simple-icons-02-brand"],
    "features-alternating-layout-03": variantsB["features-alternating-layout-03"],
    "features-simple-icons-02": variantsB["features-simple-icons-02"],
    "features-icons-and-image-01": variantsB["features-icons-and-image-01"],
    "features-icons-and-image-04": variantsB["features-icons-and-image-04"],
    "features-center-mockup-01": variantsB["features-center-mockup-01"],
    "features-icons-and-mockup-02": variantsB["features-icons-and-mockup-02"],
    "features-icons-and-mockup-05": variantsB["features-icons-and-mockup-05"],
    "features-icons-and-mockup-08": variantsB["features-icons-and-mockup-08"],
    "features-tabs-mockup-01": variantsB["features-tabs-mockup-01"],
    "features-tabs-mockup-04": variantsB["features-tabs-mockup-04"],
    "features-tabs-mockup-07": variantsB["features-tabs-mockup-07"],
    "features-tabs-mockup-10": variantsB["features-tabs-mockup-10"],
    "features-integrations-icons-01": variantsB["features-integrations-icons-01"],
    "features-integrations-icons-04": variantsB["features-integrations-icons-04"],
    "features-simple-icons-03-brand": variantsB["features-simple-icons-03-brand"],
} as const;
